/* AnalizadorAqheran.java */
/* Generated By:JavaCC: Do not edit this line. AnalizadorAqheran.java */
import java.io.*;
import java.util.ArrayList;
import java.util.List;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.charset.StandardCharsets;

public class AnalizadorAqheran implements AnalizadorAqheranConstants {

    // Listas para errores y semántica
    static ArrayList<String> listaErroresSintacticos = new ArrayList<String>();
    static ArrayList<String> listaErroresSemanticos = new ArrayList<String>();
    static TablaSimbolos tablaSimbolos = new TablaSimbolos();
    static TablaDirecciones tablaDirecciones = new TablaDirecciones();
    static PilaSemantica pilaSemantica = new PilaSemantica();
    static boolean verbose = false;

    public static void main(String[] args) {
        String archivoEntrada = null;
        for (String arg : args) {
            if (arg.equals("--aqheran")) {
                verbose = true;
            } else {
                archivoEntrada = arg;
            }
        }

        if (archivoEntrada == null) {
            System.out.println("Debe proporcionar un archivo de texto para analizar.");
            System.out.println("Uso: java AnalizadorAqheran [--aqheran] <archivo>");
            return;
        }

        try {
            String contenido = new String(Files.readAllBytes(Paths.get(archivoEntrada)), StandardCharsets.UTF_8);
            if (contenido.startsWith("\ufeff")) {
                contenido = contenido.substring(1);
            }

            AnalizadorAqheran parser = new AnalizadorAqheran(new StringReader(contenido));
            Nodo raiz = parser.parse();

            if (raiz != null) {
                if (verbose) {
                    System.out.println("\n--- ARBOL DE SINTAXIS GENERADO ---");
                    raiz.imprimir("", true);
                    System.out.println("----------------------------------");
                    tablaSimbolos.imprimir();
                    tablaDirecciones.imprimir();
                } else {
                    // Si no es verbose, imprimimos todos los tokens.
                    // Generamos una nueva instancia del analizador solo para tokenizar la entrada otra vez, o alternativamente imprimimos los de la lista guardada (si existe).
                    // Lo más simple es instanciar un TokenManager y listar tokens:
                    System.out.println("\n--- TOKENS DETECTADOS ---");
                    for (Token t : AnalizadorAqheranTokenManager.tokensDetectados) {
                        System.out.println("Token: " + t.image + " (Tipo: " + tokenImage[t.kind] + ")");
                    }
                }

                List<Cuadruplo> cuadruplos = pilaSemantica.getCuadruplos();
                if (!cuadruplos.isEmpty() && verbose) {
                    // Codigo sin optimizar
                    OptimizadorCI.imprimirOriginal(cuadruplos);

                    // Aplicar las 3 optimizaciones
                    OptimizadorCI.Resultado resOpt = OptimizadorCI.optimizar(cuadruplos);

                    // Codigo optimizado
                    OptimizadorCI.imprimirOptimizado(resOpt.optimizados);

                    // Tabla comparativa
                    OptimizadorCI.imprimirComparacion(resOpt);
                }
            }

        } catch (Exception e) {
            System.out.println(e.getMessage());
            e.printStackTrace();
        }
    }

    public Nodo parse() throws IOException {
        ArrayList<String> erroresLexicos = AnalizadorAqheranTokenManager.listaErroresLexicos;
        Nodo raiz = null;

        try {
            raiz = principal();

            if (!erroresLexicos.isEmpty()) {
                System.out.println("\n** Errores LEXICOS encontrados: **");
                for (String err : erroresLexicos) System.out.println(err);
            } else {
                System.out.println("\n** Analisis LEXICO sin errores. **");
            }

            if (!listaErroresSintacticos.isEmpty()) {
                System.out.println("\n** Errores SINTACTICOS encontrados: **");
                for (String err : listaErroresSintacticos) System.out.println(err);
            } else {

                System.out.println("\n** Analisis SINTACTICO sin errores. **");
            }

            if (!listaErroresSemanticos.isEmpty()) {
                System.out.println("\n** Errores SEMANTICOS encontrados: **");
                for (String err : listaErroresSemanticos) System.out.println(err);
            } else {
                System.out.println("\n** Analisis SEMANTICO sin errores. **");
            }

        } catch (ParseException e) {
            listaErroresSintacticos.add(manejarErrorSintactico(e));
        }
        return raiz;
    }

    static String manejarErrorSintactico(ParseException e) {
        String mensajeOriginal = e.getMessage();
        String mensajeTraducido = mensajeOriginal
            .replace("Encountered", "Encontrado")
            .replace("at line", "en la l\u00ednea")
            .replace("column", "columna")
            .replace("Was expecting:", "Se esperaba:")
            .replace("Was expecting one of:", "Se espera una de estas opciones:");

        return "Error Sintactico: " + mensajeTraducido;
    }

    // Auxiliar para comprobación de tipos
    static String verificarTipo(String t1, String t2, String op) {
        if (t1.equals("error") || t2.equals("error")) return "error";

        // Reglas de compatibilidad simples
        if (t1.equals(t2)) return t1;

        // Promoción de int a float
        if ((t1.equals("int") && t2.equals("float")) || (t1.equals("float") && t2.equals("int"))) {
            return "float";
        }

        listaErroresSemanticos.add("Error Semantico: Tipos incompatibles [" + t1 + "] y [" + t2 + "] para el operador '" + op + "'");
        return "error";
    }

    // Metodo para el Modo Panico: Salta tokens hasta encontrar uno de sincronizacion
    static void skipToNextBreakpoint(int... kinds) {
        Token t;
        boolean found = false;
        while (!found) {
            t = getToken(1);
            if (t.kind == EOF) break; // Si llega al fin del archivo, ríndete.
            // Busca en la lista de salvavidas que le pasamos.
            for (int k : kinds) {
                if (t.kind == k) {
                    found = true; //Aquí puedo volver a empezar.
                    break;
                }
            }
            if (!found) getNextToken();
        }
    }

// ==========================================
// ANALISIS SINTACTICO
// ==========================================
  static final public 
Nodo principal() throws ParseException {Nodo raiz = new Nodo("Programa"); Nodo hijo; Token tInicio, tId, tLlaveIzq, tLlaveDer, tFin;
    try {
      tInicio = jj_consume_token(INICIO);
      tId = jj_consume_token(IDENTIFICADOR);
raiz.valor = "Programa: " + tId.image;
      tLlaveIzq = jj_consume_token(LLAVEIZQ);

      label_1:
      while (true) {
        if (getToken(1).kind != EOF && !(getToken(1).kind == LLAVEDER && getToken(2).kind == FIN)) {
          ;
        } else {
          break label_1;
        }
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case FOR:
        case WHILE:
        case MATRIZ:
        case VECTOR:
        case SI:
        case SINO:
        case SWITCH:
        case BREAK:
        case CONTINUE:
        case TRY:
        case CATCH:
        case BOOL:
        case VAR:
        case CONST:
        case LEER:
        case ESCRIBIR:
        case VOID:
        case FUNC:
        case IDENTIFICADOR:{
          hijo = Codigo();
if(hijo != null) {
                        raiz.agregarHijo(hijo);
                        pilaSemantica.push(hijo);
                    }
          break;
          }
        case LLAVEDER:{
          jj_consume_token(LLAVEDER);
listaErroresSintacticos.add("Error Sintactico: Llave de cierre '}' huerfana o extra en linea " + getToken(0).beginLine);
          break;
          }
        default:
          jj_la1[0] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
      tLlaveDer = jj_consume_token(LLAVEDER);
      tFin = jj_consume_token(FIN);
{if ("" != null) return raiz;}
    } catch (ParseException e) {
listaErroresSintacticos.add(manejarErrorSintactico(e));
        skipToNextBreakpoint(FIN, EOF);
        if (getToken(1).kind == FIN) getNextToken();
        {if ("" != null) return raiz;}
    }
    throw new Error("Missing return statement in function");
}

  static final public Nodo Codigo() throws ParseException {Nodo n; Token t;
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case VAR:{
        n = declararVariable();
{if ("" != null) return n;}
        break;
        }
      case MATRIZ:
      case VECTOR:{
        n = declararArreglo();
{if ("" != null) return n;}
        break;
        }
      case CONST:{
        n = declararConstante();
{if ("" != null) return n;}
        break;
        }
      case ESCRIBIR:{
        n = gramaticaEscribir();
{if ("" != null) return n;}
        break;
        }
      case LEER:{
        n = gramaticaLeer();
{if ("" != null) return n;}
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        if (jj_2_1(2)) {
          n = gramaticaSi();
{if ("" != null) return n;}
        } else if (jj_2_2(2)) {
          n = gramaticaWhile();
{if ("" != null) return n;}
        } else if (jj_2_3(2)) {
          n = gramaticaAsignacion();
{if ("" != null) return n;}
        } else if (jj_2_4(3)) {
          n = llamarFuncion();
{if ("" != null) return n;}
        } else if (jj_2_5(2)) {
          n = gramaticaFor();
{if ("" != null) return n;}
        } else {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case BOOL:{
            n = gramaticaOperadorLogico();
{if ("" != null) return n;}
            break;
            }
          case VOID:
          case FUNC:{
            n = SentenciasFunciones();
{if ("" != null) return n;}
            break;
            }
          default:
            jj_la1[2] = jj_gen;
            if (jj_2_6(2)) {
              n = gramaticaSwitch();
{if ("" != null) return n;}
            } else if (jj_2_7(2)) {
              n = gramaticaTryCatch();
{if ("" != null) return n;}
            } else {
              switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
              case CONTINUE:{
                jj_consume_token(CONTINUE);
                jj_consume_token(DELIMITADOR);
String lCont = pilaSemantica.getLabelContinue();
                if (!lCont.equals("_")) pilaSemantica.emitirSalto(lCont);
                {if ("" != null) return new Nodo("Continue");}
                break;
                }
              case BREAK:{
                jj_consume_token(BREAK);
                jj_consume_token(DELIMITADOR);
String lBreak = pilaSemantica.getLabelBreak();
                if (!lBreak.equals("_")) pilaSemantica.emitirSalto(lBreak);
                {if ("" != null) return new Nodo("Break");}
                break;
                }
              case SINO:{
                t = jj_consume_token(SINO);
listaErroresSintacticos.add("Error Sintactico: Encontrado '" + t.image + "' huerfano o bloque anterior incompleto.");
                skipToNextBreakpoint(LLAVEDER, FIN, EOF);
                if (getToken(1).kind == LLAVEDER) getNextToken();
                {if ("" != null) return null;}
                break;
                }
              case CATCH:{
                t = jj_consume_token(CATCH);
listaErroresSintacticos.add("Error Sintactico: Encontrado '" + t.image + "' sin un bloque 'try'.");
                skipToNextBreakpoint(LLAVEDER, FIN, EOF);
                if (getToken(1).kind == LLAVEDER) getNextToken();
                {if ("" != null) return null;}
                break;
                }
              case IDENTIFICADOR:{
                t = jj_consume_token(IDENTIFICADOR);
listaErroresSintacticos.add("Error Sintactico: La palabra '" + t.image + "' en la linea " + t.beginLine + " no es una instruccion valida. Revise si escribio correctamente 'if', 'while', 'for', 'aqhe', etc.");
                // Recuperación: saltamos hasta el siguiente punto estable (punto y coma o llave de cierre)
                // para evitar errores en cascada.
                skipToNextBreakpoint(DELIMITADOR, LLAVEDER, FIN, EOF);
                if (getToken(1).kind == DELIMITADOR || getToken(1).kind == LLAVEDER) getNextToken();
                {if ("" != null) return null;}
                break;
                }
              default:
                jj_la1[3] = jj_gen;
                jj_consume_token(-1);
                throw new ParseException();
              }
            }
          }
        }
      }
    } catch (ParseException e) {
listaErroresSintacticos.add(manejarErrorSintactico(e));
        skipToNextBreakpoint(DELIMITADOR, LLAVEDER, FIN, EOF);
        if (getToken(1).kind == DELIMITADOR || getToken(1).kind == LLAVEDER) getNextToken();
        {if ("" != null) return null;}
    }
    throw new Error("Missing return statement in function");
}

  static final public Nodo declararVariable() throws ParseException {Token t; Nodo n = new Nodo("Declaracion Variable"); String tipo;
    try {
      jj_consume_token(VAR);
      t = jj_consume_token(IDENTIFICADOR);
      tipo = tipoDato();
      jj_consume_token(DELIMITADOR);
try {
                tablaSimbolos.insertar(t.image, tipo);
            } catch (Exception e) {
                listaErroresSemanticos.add(e.getMessage());
            }
            // 2.3.1 – emitir valor por defecto al declarar la variable
            String valorDefault = tipo.equals("float") ? "0.0" : tipo.equals("bool") ? "false" : tipo.equals("string") ? "\"\"" : "0";
            pilaSemantica.emitirAsignacion(valorDefault, t.image);
            n.agregarHijo(new Nodo(t.image, tipo));
            {if ("" != null) return n;}
    } catch (ParseException e) {
listaErroresSintacticos.add(manejarErrorSintactico(e));
        skipToNextBreakpoint(DELIMITADOR, LLAVEDER, FIN, EOF);
        if (getToken(1).kind == DELIMITADOR) getNextToken();
        {if ("" != null) return null;}
    }
    throw new Error("Missing return statement in function");
}

  static final public Nodo declararConstante() throws ParseException {Token t; Nodo n = new Nodo("Declaracion Constante"); String tipo; Nodo v;
    try {
      jj_consume_token(CONST);
      t = jj_consume_token(IDENTIFICADOR);
      tipo = tipoDato();
      jj_consume_token(IGUAL);
      v = valor();
      jj_consume_token(DELIMITADOR);
try {
                tablaSimbolos.insertar(t.image, tipo);
                // Comprobar que el valor asignado sea compatible con el tipo declarado
                verificarTipo(tipo, v.tipo, "=");
            } catch (Exception e) {
                listaErroresSemanticos.add(e.getMessage());
            }
            // 2.3.1 – emitir asignacion de la constante
            pilaSemantica.emitirAsignacion(v.valor, t.image);
            Nodo c = new Nodo(t.image, tipo);
            c.agregarHijo(v);
            n.agregarHijo(c);
            {if ("" != null) return n;}
    } catch (ParseException e) {
listaErroresSintacticos.add(manejarErrorSintactico(e));
        skipToNextBreakpoint(DELIMITADOR, LLAVEDER, FIN, EOF);
        if (getToken(1).kind == DELIMITADOR) getNextToken();
        {if ("" != null) return null;}
    }
    throw new Error("Missing return statement in function");
}

  static final public String tipoDato() throws ParseException {Token t;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INT:{
      t = jj_consume_token(INT);
{if ("" != null) return t.image;}
      break;
      }
    case FLOAT:{
      t = jj_consume_token(FLOAT);
{if ("" != null) return t.image;}
      break;
      }
    case BOOL:{
      t = jj_consume_token(BOOL);
{if ("" != null) return t.image;}
      break;
      }
    case STRING:{
      t = jj_consume_token(STRING);
{if ("" != null) return t.image;}
      break;
      }
    default:
      jj_la1[4] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  static final public Nodo valor() throws ParseException {Token t; Nodo n;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ENTEROS:{
      t = jj_consume_token(ENTEROS);
n = new Nodo(t.image, "int"); pilaSemantica.push(n); tablaDirecciones.insertar(t.image); {if ("" != null) return n;}
      break;
      }
    case VCAD:{
      t = jj_consume_token(VCAD);
n = new Nodo(t.image, "string"); pilaSemantica.push(n); tablaDirecciones.insertar(t.image); {if ("" != null) return n;}
      break;
      }
    case NUMERODECIMAL:{
      t = jj_consume_token(NUMERODECIMAL);
n = new Nodo(t.image, "float"); pilaSemantica.push(n); tablaDirecciones.insertar(t.image); {if ("" != null) return n;}
      break;
      }
    case HEX_LITERAL:{
      t = jj_consume_token(HEX_LITERAL);
n = new Nodo(t.image, "int"); pilaSemantica.push(n); tablaDirecciones.insertar(t.image); {if ("" != null) return n;}
      break;
      }
    case TRUE:{
      t = jj_consume_token(TRUE);
n = new Nodo(t.image, "bool"); pilaSemantica.push(n); tablaDirecciones.insertar(t.image); {if ("" != null) return n;}
      break;
      }
    case FALSE:{
      t = jj_consume_token(FALSE);
n = new Nodo(t.image, "bool"); pilaSemantica.push(n); tablaDirecciones.insertar(t.image); {if ("" != null) return n;}
      break;
      }
    case NULL:{
      t = jj_consume_token(NULL);
n = new Nodo(t.image, "null"); pilaSemantica.push(n); tablaDirecciones.insertar(t.image); {if ("" != null) return n;}
      break;
      }
    case PARENIZQ:{
      jj_consume_token(PARENIZQ);
      n = operacionSimple();
      jj_consume_token(PARENDER);
{if ("" != null) return n;}
      break;
      }
    default:
      jj_la1[5] = jj_gen;
      if (jj_2_8(2147483647)) {
        t = jj_consume_token(IDENTIFICADOR);
        jj_consume_token(CORCHIZQ);
        n = operacionSimple();
        jj_consume_token(CORCHDER);
String tipoBase = "error";
          try {
              String tipoArray = tablaSimbolos.obtenerTipo(t.image);
              tipoBase = tipoArray.startsWith("array_") ? tipoArray.substring(6) : tipoArray;
          } catch (Exception e) {
              listaErroresSemanticos.add(e.getMessage());
          }
          String temp = pilaSemantica.nuevaTemporal();
          pilaSemantica.emitir("[]", t.image, n.valor, temp);
          Nodo acceso = new Nodo(temp, tipoBase);
          pilaSemantica.push(acceso);
          {if ("" != null) return acceso;}
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case IDENTIFICADOR:{
          t = jj_consume_token(IDENTIFICADOR);
String tipo = "error";
          try {
              tipo = tablaSimbolos.obtenerTipo(t.image);
          } catch (Exception e) {
              listaErroresSemanticos.add(e.getMessage());
          }
          n = new Nodo(t.image, tipo);
          pilaSemantica.push(n);
          {if ("" != null) return n;}
          break;
          }
        default:
          jj_la1[6] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
    throw new Error("Missing return statement in function");
}

  static final public Nodo gramaticaEscribir() throws ParseException {Nodo n = new Nodo("Escribir"); Nodo hijo; Token t;
    try {
      jj_consume_token(ESCRIBIR);
      jj_consume_token(PARENIZQ);
      label_2:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case VCAD:{
          t = jj_consume_token(VCAD);
n.agregarHijo(new Nodo(t.image, "string")); pilaSemantica.emitirWrite(t.image);
          break;
          }
        case IDENTIFICADOR:{
          t = jj_consume_token(IDENTIFICADOR);
n.agregarHijo(new Nodo(t.image, "id")); pilaSemantica.emitirWrite(t.image);
          break;
          }
        default:
          jj_la1[7] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        label_3:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case CONCATENAR:{
            ;
            break;
            }
          default:
            jj_la1[8] = jj_gen;
            break label_3;
          }
          jj_consume_token(CONCATENAR);
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case VCAD:{
            t = jj_consume_token(VCAD);
n.agregarHijo(new Nodo(t.image, "string")); pilaSemantica.emitirWrite(t.image);
            break;
            }
          case IDENTIFICADOR:{
            t = jj_consume_token(IDENTIFICADOR);
n.agregarHijo(new Nodo(t.image, "id")); pilaSemantica.emitirWrite(t.image);
            break;
            }
          default:
            jj_la1[9] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
        }
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case VCAD:
        case IDENTIFICADOR:{
          ;
          break;
          }
        default:
          jj_la1[10] = jj_gen;
          break label_2;
        }
      }
      jj_consume_token(PARENDER);
      jj_consume_token(DELIMITADOR);
{if ("" != null) return n;}
    } catch (ParseException e) {
listaErroresSintacticos.add(manejarErrorSintactico(e));
        skipToNextBreakpoint(DELIMITADOR, LLAVEDER, FIN, EOF);
        if (getToken(1).kind == DELIMITADOR) getNextToken();
        {if ("" != null) return null;}
    }
    throw new Error("Missing return statement in function");
}

  static final public Nodo gramaticaLeer() throws ParseException {Token t; Nodo n = new Nodo("Leer");
    try {
      jj_consume_token(LEER);
      jj_consume_token(PARENIZQ);
      t = jj_consume_token(IDENTIFICADOR);
      jj_consume_token(PARENDER);
      jj_consume_token(DELIMITADOR);
n.agregarHijo(new Nodo(t.image, "id"));
            pilaSemantica.emitirRead(t.image);
            {if ("" != null) return n;}
    } catch (ParseException e) {
listaErroresSintacticos.add(manejarErrorSintactico(e));
        skipToNextBreakpoint(DELIMITADOR, LLAVEDER, FIN, EOF);
        if (getToken(1).kind == DELIMITADOR) getNextToken();
        {if ("" != null) return null;}
    }
    throw new Error("Missing return statement in function");
}

  static final public Nodo gramaticaSi() throws ParseException {Nodo n = new Nodo("Si (IF)"); Nodo cond, hijo, sino; String lElse, lFin;
    try {
      jj_consume_token(SI);
      jj_consume_token(PARENIZQ);
      cond = condicion();
      jj_consume_token(PARENDER);
n.agregarHijo(cond);
            lElse = pilaSemantica.nuevaEtiqueta();
            lFin = pilaSemantica.nuevaEtiqueta();
            pilaSemantica.emitirSaltoCondicional(cond.valor, lElse);
      jj_consume_token(LLAVEIZQ);
      label_4:
      while (true) {
        hijo = Codigo();
n.agregarHijo(hijo);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case FOR:
        case WHILE:
        case MATRIZ:
        case VECTOR:
        case SI:
        case SINO:
        case SWITCH:
        case BREAK:
        case CONTINUE:
        case TRY:
        case CATCH:
        case BOOL:
        case VAR:
        case CONST:
        case LEER:
        case ESCRIBIR:
        case VOID:
        case FUNC:
        case IDENTIFICADOR:{
          ;
          break;
          }
        default:
          jj_la1[11] = jj_gen;
          break label_4;
        }
      }
      jj_consume_token(LLAVEDER);
pilaSemantica.emitirSalto(lFin);
            pilaSemantica.emitirLabel(lElse);
      label_5:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case SINO:{
          ;
          break;
          }
        default:
          jj_la1[12] = jj_gen;
          break label_5;
        }
        sino = gramaticaSiNo();
n.agregarHijo(sino);
      }
pilaSemantica.emitirLabel(lFin);
            {if ("" != null) return n;}
    } catch (ParseException e) {
listaErroresSintacticos.add(manejarErrorSintactico(e));
        skipToNextBreakpoint(LLAVEDER, FIN, EOF);
        if (getToken(1).kind == LLAVEDER) getNextToken();
        {if ("" != null) return null;}
    }
    throw new Error("Missing return statement in function");
}

  static final public Nodo gramaticaSiNo() throws ParseException {Nodo n = new Nodo("Sino (ELSE)"); Nodo hijo;
    try {
      jj_consume_token(SINO);
      jj_consume_token(LLAVEIZQ);
      label_6:
      while (true) {
        hijo = Codigo();
n.agregarHijo(hijo);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case FOR:
        case WHILE:
        case MATRIZ:
        case VECTOR:
        case SI:
        case SINO:
        case SWITCH:
        case BREAK:
        case CONTINUE:
        case TRY:
        case CATCH:
        case BOOL:
        case VAR:
        case CONST:
        case LEER:
        case ESCRIBIR:
        case VOID:
        case FUNC:
        case IDENTIFICADOR:{
          ;
          break;
          }
        default:
          jj_la1[13] = jj_gen;
          break label_6;
        }
      }
      jj_consume_token(LLAVEDER);
{if ("" != null) return n;}
    } catch (ParseException e) {
listaErroresSintacticos.add(manejarErrorSintactico(e));
        skipToNextBreakpoint(LLAVEDER, FIN, EOF);
        if (getToken(1).kind == LLAVEDER) getNextToken();
        {if ("" != null) return null;}
    }
    throw new Error("Missing return statement in function");
}

  static final public Nodo condicion() throws ParseException {Nodo izq, der, log; Token t;
    try {
      izq = valor();
      t = OperadoresComparadores();
      der = valor();
String tipoRes = verificarTipo(izq.tipo, der.tipo, t.image);
            if (!tipoRes.equals("error")) tipoRes = "bool";
            String tempCond = pilaSemantica.nuevaTemporal(); // 2.3.2 – temporal determinista
            Nodo raiz = new Nodo(tempCond, tipoRes);
            raiz.agregarHijo(izq);
            raiz.agregarHijo(der);
            // Emitir cuadruplo de comparacion
            pilaSemantica.emitir(t.image, izq.valor, der.valor, tempCond);
      label_7:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case AND:
        case OR:
        case NOT:{
          ;
          break;
          }
        default:
          jj_la1[14] = jj_gen;
          break label_7;
        }
        log = condicionLogicos();
raiz.agregarHijo(log);
      }
{if ("" != null) return raiz;}
    } catch (ParseException e) {
listaErroresSintacticos.add(manejarErrorSintactico(e));
        skipToNextBreakpoint(PARENDER, LLAVEIZQ, DELIMITADOR, FIN, EOF);
        if (getToken(1).kind == PARENDER) getNextToken();
        {if ("" != null) return null;}
    }
    throw new Error("Missing return statement in function");
}

  static final public Nodo condicionLogicos() throws ParseException {Nodo n; Token t; Nodo v1, v2; Token comp;
    try {
      t = OperadoresLogicos();
      v1 = valor();
      comp = OperadoresComparadores();
      v2 = valor();
Nodo raiz = new Nodo(t.image, "logico");
            Nodo comparisons = new Nodo(comp.image, "comparador");
            comparisons.agregarHijo(v1);
            comparisons.agregarHijo(v2);
            raiz.agregarHijo(comparisons);
            {if ("" != null) return raiz;}
    } catch (ParseException e) {
listaErroresSintacticos.add(manejarErrorSintactico(e));
        skipToNextBreakpoint(PARENDER, LLAVEIZQ, DELIMITADOR, FIN, EOF);
        {if ("" != null) return null;}
    }
    throw new Error("Missing return statement in function");
}

  static final public Token OperadoresLogicos() throws ParseException {Token t;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case AND:{
      t = jj_consume_token(AND);
{if ("" != null) return t;}
      break;
      }
    case OR:{
      t = jj_consume_token(OR);
{if ("" != null) return t;}
      break;
      }
    case NOT:{
      t = jj_consume_token(NOT);
{if ("" != null) return t;}
      break;
      }
    default:
      jj_la1[15] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  static final public Token OperadoresComparadores() throws ParseException {Token t;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IGUALDAD:{
      t = jj_consume_token(IGUALDAD);
{if ("" != null) return t;}
      break;
      }
    case DESIGUALDAD:{
      t = jj_consume_token(DESIGUALDAD);
{if ("" != null) return t;}
      break;
      }
    case MAYOR:{
      t = jj_consume_token(MAYOR);
{if ("" != null) return t;}
      break;
      }
    case MENOR:{
      t = jj_consume_token(MENOR);
{if ("" != null) return t;}
      break;
      }
    case MAYORIGUAL:{
      t = jj_consume_token(MAYORIGUAL);
{if ("" != null) return t;}
      break;
      }
    case MENORIGUAL:{
      t = jj_consume_token(MENORIGUAL);
{if ("" != null) return t;}
      break;
      }
    default:
      jj_la1[16] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  static final public Nodo gramaticaWhile() throws ParseException {Nodo n = new Nodo("While"); Nodo cond, hijo; String lInicio, lFin;
    try {
      jj_consume_token(WHILE);
lInicio = pilaSemantica.nuevaEtiqueta();
            lFin    = pilaSemantica.nuevaEtiqueta();
            pilaSemantica.emitirLabel(lInicio);
            pilaSemantica.entrarBucle(lFin, lInicio);  // break→lFin  continue→lInicio

      jj_consume_token(PARENIZQ);
      cond = condicion();
      jj_consume_token(PARENDER);
n.agregarHijo(cond);
            pilaSemantica.emitirSaltoCondicional(cond.valor, lFin);
      jj_consume_token(LLAVEIZQ);
      label_8:
      while (true) {
        hijo = Codigo();
n.agregarHijo(hijo);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case FOR:
        case WHILE:
        case MATRIZ:
        case VECTOR:
        case SI:
        case SINO:
        case SWITCH:
        case BREAK:
        case CONTINUE:
        case TRY:
        case CATCH:
        case BOOL:
        case VAR:
        case CONST:
        case LEER:
        case ESCRIBIR:
        case VOID:
        case FUNC:
        case IDENTIFICADOR:{
          ;
          break;
          }
        default:
          jj_la1[17] = jj_gen;
          break label_8;
        }
      }
      jj_consume_token(LLAVEDER);
pilaSemantica.emitirSalto(lInicio);
            pilaSemantica.emitirLabel(lFin);
            pilaSemantica.salirBucle();
            {if ("" != null) return n;}
    } catch (ParseException e) {
listaErroresSintacticos.add(manejarErrorSintactico(e));
        skipToNextBreakpoint(LLAVEDER, FIN, EOF);
        if (getToken(1).kind == LLAVEDER) getNextToken();
        {if ("" != null) return null;}
    }
    throw new Error("Missing return statement in function");
}

  static final public Nodo gramaticaAsignacion() throws ParseException {Token t; Nodo e; Nodo n = new Nodo("Asignacion"); Token op = null; Nodo idx = null;
    try {
      t = jj_consume_token(IDENTIFICADOR);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case CORCHIZQ:{
        jj_consume_token(CORCHIZQ);
        idx = operacionSimple();
        jj_consume_token(CORCHDER);
        jj_consume_token(IGUAL);
        e = operacionSimple();
        break;
        }
      case IGUAL:{
        jj_consume_token(IGUAL);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case ENTEROS:
        case NUMERODECIMAL:
        case HEX_LITERAL:
        case VCAD:
        case TRUE:
        case FALSE:
        case NULL:
        case PARENIZQ:
        case IDENTIFICADOR:{
          e = operacionSimple();
          break;
          }
        case FUNC:{
          e = asignacionConFuncion();
          break;
          }
        default:
          jj_la1[18] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
        }
      case ASIG_SUMA:
      case ASIG_RESTA:
      case ASIG_MULT:
      case ASIG_DIV:{
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case ASIG_SUMA:{
          op = jj_consume_token(ASIG_SUMA);
          break;
          }
        case ASIG_RESTA:{
          op = jj_consume_token(ASIG_RESTA);
          break;
          }
        case ASIG_MULT:{
          op = jj_consume_token(ASIG_MULT);
          break;
          }
        case ASIG_DIV:{
          op = jj_consume_token(ASIG_DIV);
          break;
          }
        default:
          jj_la1[19] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        e = operacionSimple();
        break;
        }
      default:
        jj_la1[20] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(DELIMITADOR);
String tipoDestino = "error";
            try {
                tipoDestino = tablaSimbolos.obtenerTipo(t.image);
                verificarTipo(tipoDestino, e.tipo, "=");
            } catch (Exception e_sem) {
                listaErroresSemanticos.add(e_sem.getMessage());
            }
            n.tipo = tipoDestino;
            n.agregarHijo(e);

            if (idx != null) {
                // ([]=, valor, indice, arreglo)
                pilaSemantica.emitir("[]=", e.valor, idx.valor, t.image);
                n.valor = "Asignacion Array: " + t.image;
            } else if (op != null) {
                // x op= e  →  T = x op e ; x = T
                String opStr = op.image.replace("=", "");
                String temp  = pilaSemantica.nuevaTemporal();
                pilaSemantica.emitir(opStr, t.image, e.valor, temp);
                pilaSemantica.emitirAsignacion(temp, t.image);
                n.valor = "Asignacion: " + t.image;
            } else {
                pilaSemantica.emitirAsignacion(e.valor, t.image);
                n.valor = "Asignacion: " + t.image;
            }

            {if ("" != null) return n;}
    } catch (ParseException e_arg) {
listaErroresSintacticos.add(manejarErrorSintactico(e_arg));
        skipToNextBreakpoint(DELIMITADOR, LLAVEDER, FIN, EOF);
        if (getToken(1).kind == DELIMITADOR) getNextToken();
        {if ("" != null) return null;}
    }
    throw new Error("Missing return statement in function");
}

  static final public Nodo operacionSimple() throws ParseException {Nodo izq, der; Token t;
    try {
      izq = termino();
      label_9:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case MAS:
        case MENOS:{
          ;
          break;
          }
        default:
          jj_la1[21] = jj_gen;
          break label_9;
        }
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case MAS:{
          t = jj_consume_token(MAS);
          break;
          }
        case MENOS:{
          t = jj_consume_token(MENOS);
          break;
          }
        default:
          jj_la1[22] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        der = termino();
// La Pila Semántica ya tiene los operandos (izq y der) en orden (izq, der)
                // Sacamos los dos últimos haciendo el casteo a Nodo
                Nodo opDer = (Nodo) pilaSemantica.pop();
                Nodo opIzq = (Nodo) pilaSemantica.pop();

                String tipoRes = verificarTipo(opIzq.tipo, opDer.tipo, t.image);

                // Generamos nodo temporal T# en la pila y emitimos el cuadruplo (op, arg1, arg2, T#)
                Nodo raiz = pilaSemantica.generarTemporal(tipoRes, t.image, opIzq.valor, opDer.valor);
                raiz.agregarHijo(opIzq);
                raiz.agregarHijo(opDer);
                izq = raiz;
      }
{if ("" != null) return izq;}
    } catch (ParseException e) {
listaErroresSintacticos.add(manejarErrorSintactico(e));
        skipToNextBreakpoint(DELIMITADOR, LLAVEDER, FIN, EOF);
        {if ("" != null) return null;}
    }
    throw new Error("Missing return statement in function");
}

  static final public Nodo termino() throws ParseException {Nodo izq, der; Token t;
    izq = valor();
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MULT:
      case DIV:
      case MOD:{
        ;
        break;
        }
      default:
        jj_la1[23] = jj_gen;
        break label_10;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MULT:{
        t = jj_consume_token(MULT);
        break;
        }
      case DIV:{
        t = jj_consume_token(DIV);
        break;
        }
      case MOD:{
        t = jj_consume_token(MOD);
        break;
        }
      default:
        jj_la1[24] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      der = valor();
Nodo opDer = (Nodo) pilaSemantica.pop();
            Nodo opIzq = (Nodo) pilaSemantica.pop();

            String tipoRes = verificarTipo(opIzq.tipo, opDer.tipo, t.image);

            // Generamos nodo temporal T# y emitimos cuadruplo (op, arg1, arg2, T#)
            Nodo raiz = pilaSemantica.generarTemporal(tipoRes, t.image, opIzq.valor, opDer.valor);
            raiz.agregarHijo(opIzq);
            raiz.agregarHijo(opDer);
            izq = raiz;
    }
{if ("" != null) return izq;}
    throw new Error("Missing return statement in function");
}

  static final public Nodo gramaticaOperadorLogico() throws ParseException {Token t; Token id; Nodo cond; Nodo n = new Nodo("Asignacion Logica");
    try {
      jj_consume_token(BOOL);
      id = jj_consume_token(IDENTIFICADOR);
      jj_consume_token(IGUAL);
      cond = condicionLogico();
      jj_consume_token(DELIMITADOR);
n.valor = "Asignacion Logica: " + id.image;
            n.agregarHijo(cond);
            {if ("" != null) return n;}
    } catch (ParseException e) {
listaErroresSintacticos.add(manejarErrorSintactico(e));
        skipToNextBreakpoint(DELIMITADOR, LLAVEDER, FIN, EOF);
        if (getToken(1).kind == DELIMITADOR) getNextToken();
        {if ("" != null) return null;}
    }
    throw new Error("Missing return statement in function");
}

  static final public Nodo condicionLogico() throws ParseException {Nodo izq, der; Token t;
    try {
      izq = valor();
      t = OperadoresLogicos();
      der = valor();
Nodo raiz = new Nodo(t.image, "logico");
            raiz.agregarHijo(izq);
            raiz.agregarHijo(der);
            {if ("" != null) return raiz;}
    } catch (ParseException e) {
listaErroresSintacticos.add(manejarErrorSintactico(e));
        skipToNextBreakpoint(DELIMITADOR, LLAVEDER, FIN, EOF);
        {if ("" != null) return null;}
    }
    throw new Error("Missing return statement in function");
}

// 2.3.4 – for con IR completo (init, condicion, incremento, etiquetas)
  static final public Nodo gramaticaFor() throws ParseException {Nodo n = new Nodo("For"); Nodo hijo;
    Token idInit, valInit, idCond, idInc; Token comp, inc; Nodo valCond;
    String tipoInit, lInicio, lFin, tempCond, tempInc;
    try {
      jj_consume_token(FOR);
      jj_consume_token(PARENIZQ);
      // -- inicializacion: tipo id = litoral ;
              tipoInit = tipoDato();
      idInit = jj_consume_token(IDENTIFICADOR);
      jj_consume_token(IGUAL);
      valInit = jj_consume_token(ENTEROS);
      jj_consume_token(DELIMITADOR);
try { tablaSimbolos.insertar(idInit.image, tipoInit); }
            catch(Exception e) { listaErroresSemanticos.add(e.getMessage()); }
            pilaSemantica.emitirAsignacion(valInit.image, idInit.image);
            lInicio = pilaSemantica.nuevaEtiqueta();
            lFin    = pilaSemantica.nuevaEtiqueta();
            pilaSemantica.emitirLabel(lInicio);
            pilaSemantica.entrarBucle(lFin, lInicio);
      // -- condicion: id comp valor ;
              idCond = jj_consume_token(IDENTIFICADOR);
      comp = OperadoresComparadores();
      valCond = valor();
      jj_consume_token(DELIMITADOR);
tempCond = pilaSemantica.nuevaTemporal();
            pilaSemantica.emitir(comp.image, idCond.image, valCond.valor, tempCond);
            pilaSemantica.emitirSaltoCondicional(tempCond, lFin);
            n.agregarHijo(new Nodo(tempCond, "bool"));
      // -- incremento: ++/-- id
              inc = operadorIncDec();
      idInc = jj_consume_token(IDENTIFICADOR);
n.agregarHijo(new Nodo("Paso: " + inc.image + idInc.image));
      jj_consume_token(PARENDER);
      jj_consume_token(LLAVEIZQ);
      label_11:
      while (true) {
        hijo = Codigo();
n.agregarHijo(hijo);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case FOR:
        case WHILE:
        case MATRIZ:
        case VECTOR:
        case SI:
        case SINO:
        case SWITCH:
        case BREAK:
        case CONTINUE:
        case TRY:
        case CATCH:
        case BOOL:
        case VAR:
        case CONST:
        case LEER:
        case ESCRIBIR:
        case VOID:
        case FUNC:
        case IDENTIFICADOR:{
          ;
          break;
          }
        default:
          jj_la1[25] = jj_gen;
          break label_11;
        }
      }
      jj_consume_token(LLAVEDER);
String incOp = inc.image.equals("++") ? "+" : "-";
            tempInc = pilaSemantica.nuevaTemporal();
            pilaSemantica.emitir(incOp, idInc.image, "1", tempInc);
            pilaSemantica.emitirAsignacion(tempInc, idInc.image);
            pilaSemantica.emitirSalto(lInicio);
            pilaSemantica.emitirLabel(lFin);
            pilaSemantica.salirBucle();
            {if ("" != null) return n;}
    } catch (ParseException e) {
listaErroresSintacticos.add(manejarErrorSintactico(e));
        skipToNextBreakpoint(LLAVEDER, FIN, EOF);
        if (getToken(1).kind == LLAVEDER) getNextToken();
        {if ("" != null) return null;}
    }
    throw new Error("Missing return statement in function");
}

  static final public Token operadorIncDec() throws ParseException {Token t;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INC:{
      t = jj_consume_token(INC);
{if ("" != null) return t;}
      break;
      }
    case DEC:{
      t = jj_consume_token(DEC);
{if ("" != null) return t;}
      break;
      }
    default:
      jj_la1[26] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  static final public Nodo SentenciasFunciones() throws ParseException {Token id; String tipo; Nodo param = null, hijo, ret; Nodo n;
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case FUNC:{
        jj_consume_token(FUNC);
        tipo = tipoDato();
        id = jj_consume_token(IDENTIFICADOR);
try {
                  tablaSimbolos.insertar(id.image, tipo);
              } catch (Exception e_sem) {
                  listaErroresSemanticos.add(e_sem.getMessage());
              }
              tablaSimbolos.entrarScope();
              pilaSemantica.emitirLabel("fn_" + id.image);
        jj_consume_token(PARENIZQ);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case IDENTIFICADOR:{
          param = parametros();
          break;
          }
        default:
          jj_la1[27] = jj_gen;
          ;
        }
        jj_consume_token(PARENDER);
        jj_consume_token(LLAVEIZQ);
n = new Nodo("Funcion: " + id.image, tipo);
              if (param != null) n.agregarHijo(param);
        label_12:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case FOR:
          case WHILE:
          case MATRIZ:
          case VECTOR:
          case SI:
          case SINO:
          case SWITCH:
          case BREAK:
          case CONTINUE:
          case TRY:
          case CATCH:
          case BOOL:
          case VAR:
          case CONST:
          case LEER:
          case ESCRIBIR:
          case VOID:
          case FUNC:
          case IDENTIFICADOR:{
            ;
            break;
            }
          default:
            jj_la1[28] = jj_gen;
            break label_12;
          }
          hijo = Codigo();
n.agregarHijo(hijo);
        }
        jj_consume_token(RETURN);
        ret = valor();
        jj_consume_token(DELIMITADOR);
        jj_consume_token(LLAVEDER);
        jj_consume_token(DELIMITADOR);
verificarTipo(tipo, ret.tipo, "return");
              Nodo retNode = new Nodo("Return", ret.tipo);
              retNode.agregarHijo(ret);
              n.agregarHijo(retNode);
              pilaSemantica.emitirReturn(ret.valor);
              tablaSimbolos.salirScope();
              {if ("" != null) return n;}
        break;
        }
      case VOID:{
        jj_consume_token(VOID);
        id = jj_consume_token(IDENTIFICADOR);
try {
                  tablaSimbolos.insertar(id.image, "void");
              } catch (Exception e_sem) {
                  listaErroresSemanticos.add(e_sem.getMessage());
              }
              tablaSimbolos.entrarScope();
              pilaSemantica.emitirLabel("fn_" + id.image);
        jj_consume_token(PARENIZQ);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case IDENTIFICADOR:{
          param = parametros();
          break;
          }
        default:
          jj_la1[29] = jj_gen;
          ;
        }
        jj_consume_token(PARENDER);
        jj_consume_token(LLAVEIZQ);
n = new Nodo("Procedimiento: " + id.image, "void");
              if (param != null) n.agregarHijo(param);
        label_13:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case FOR:
          case WHILE:
          case MATRIZ:
          case VECTOR:
          case SI:
          case SINO:
          case SWITCH:
          case BREAK:
          case CONTINUE:
          case TRY:
          case CATCH:
          case BOOL:
          case VAR:
          case CONST:
          case LEER:
          case ESCRIBIR:
          case VOID:
          case FUNC:
          case IDENTIFICADOR:{
            ;
            break;
            }
          default:
            jj_la1[30] = jj_gen;
            break label_13;
          }
          hijo = Codigo();
n.agregarHijo(hijo);
        }
        jj_consume_token(LLAVEDER);
        jj_consume_token(DELIMITADOR);
tablaSimbolos.salirScope();
              {if ("" != null) return n;}
        break;
        }
      default:
        jj_la1[31] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException e) {
listaErroresSintacticos.add(manejarErrorSintactico(e));
        skipToNextBreakpoint(DELIMITADOR, LLAVEDER, FIN, EOF);
        if (getToken(1).kind == DELIMITADOR) getNextToken();
        {if ("" != null) return null;}
    }
    throw new Error("Missing return statement in function");
}

  static final public Nodo parametros() throws ParseException {Token id; String tipo; Nodo n = new Nodo("Parametros");
    try {
      id = jj_consume_token(IDENTIFICADOR);
      tipo = tipoDato();
n.agregarHijo(new Nodo(id.image, tipo));
            try { tablaSimbolos.insertar(id.image, tipo); } catch(Exception e_p) { listaErroresSemanticos.add(e_p.getMessage()); }
      label_14:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMA:{
          ;
          break;
          }
        default:
          jj_la1[32] = jj_gen;
          break label_14;
        }
        jj_consume_token(COMA);
        id = jj_consume_token(IDENTIFICADOR);
        tipo = tipoDato();
n.agregarHijo(new Nodo(id.image, tipo));
            try { tablaSimbolos.insertar(id.image, tipo); } catch(Exception e_p) { listaErroresSemanticos.add(e_p.getMessage()); }
      }
{if ("" != null) return n;}
    } catch (ParseException e) {
listaErroresSintacticos.add(manejarErrorSintactico(e));
        skipToNextBreakpoint(PARENDER, LLAVEIZQ, DELIMITADOR, FIN, EOF);
        {if ("" != null) return null;}
    }
    throw new Error("Missing return statement in function");
}

  static final public Nodo llamarFuncion() throws ParseException {Token id; Nodo v; Nodo n = new Nodo("Llamada Funcion"); int numArgs = 0;
    try {
      jj_consume_token(FUNC);
      id = jj_consume_token(IDENTIFICADOR);
n.valor = "Llamada: " + id.image;
      jj_consume_token(PARENIZQ);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ENTEROS:
      case NUMERODECIMAL:
      case HEX_LITERAL:
      case VCAD:
      case TRUE:
      case FALSE:
      case NULL:
      case PARENIZQ:
      case IDENTIFICADOR:{
        v = valor();
n.agregarHijo(v); numArgs++; pilaSemantica.emitir("PARAM", v.valor, "_", "_");
        label_15:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case COMA:{
            ;
            break;
            }
          default:
            jj_la1[33] = jj_gen;
            break label_15;
          }
          jj_consume_token(COMA);
          v = valor();
n.agregarHijo(v); numArgs++; pilaSemantica.emitir("PARAM", v.valor, "_", "_");
        }
        break;
        }
      default:
        jj_la1[34] = jj_gen;
        ;
      }
      jj_consume_token(PARENDER);
      jj_consume_token(DELIMITADOR);
pilaSemantica.emitirCall(id.image, numArgs, "_");
            {if ("" != null) return n;}
    } catch (ParseException e) {
listaErroresSintacticos.add(manejarErrorSintactico(e));
        skipToNextBreakpoint(DELIMITADOR, LLAVEDER, FIN, EOF);
        if (getToken(1).kind == DELIMITADOR) getNextToken();
        {if ("" != null) return null;}
    }
    throw new Error("Missing return statement in function");
}

  static final public Nodo asignacionConFuncion() throws ParseException {Token id; Nodo v; Nodo n = new Nodo("Llamada Funcion"); int numArgs = 0;
    try {
      jj_consume_token(FUNC);
      id = jj_consume_token(IDENTIFICADOR);
String tipoRet = "error";
            try {
                tipoRet = tablaSimbolos.obtenerTipo(id.image);
            } catch (Exception e) {
                listaErroresSemanticos.add(e.getMessage());
            }
            n.valor = "Llamada: " + id.image;
            n.tipo = tipoRet;
      jj_consume_token(PARENIZQ);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ENTEROS:
      case NUMERODECIMAL:
      case HEX_LITERAL:
      case VCAD:
      case TRUE:
      case FALSE:
      case NULL:
      case PARENIZQ:
      case IDENTIFICADOR:{
        v = valor();
n.agregarHijo(v); numArgs++; pilaSemantica.emitir("PARAM", v.valor, "_", "_");
        label_16:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case COMA:{
            ;
            break;
            }
          default:
            jj_la1[35] = jj_gen;
            break label_16;
          }
          jj_consume_token(COMA);
          v = valor();
n.agregarHijo(v); numArgs++; pilaSemantica.emitir("PARAM", v.valor, "_", "_");
        }
        break;
        }
      default:
        jj_la1[36] = jj_gen;
        ;
      }
      jj_consume_token(PARENDER);
String tempRet = "T_ret_" + id.image;
            pilaSemantica.emitirCall(id.image, numArgs, tempRet);
            n.valor = tempRet;
            {if ("" != null) return n;}
    } catch (ParseException e) {
listaErroresSintacticos.add(manejarErrorSintactico(e));
        skipToNextBreakpoint(PARENDER, DELIMITADOR, LLAVEDER, FIN, EOF);
        {if ("" != null) return null;}
    }
    throw new Error("Missing return statement in function");
}

// 2.3.4 – switch con IR: comparacion por caso, saltos y etiquetas
  static final public Nodo gramaticaSwitch() throws ParseException {Nodo n = new Nodo("Switch"); Token t; Nodo hijo; String lFin;
    try {
      jj_consume_token(SWITCH);
      jj_consume_token(PARENIZQ);
      t = jj_consume_token(IDENTIFICADOR);
      jj_consume_token(PARENDER);
      jj_consume_token(LLAVEIZQ);
n.agregarHijo(new Nodo("Variable: " + t.image, "id"));
            lFin = pilaSemantica.nuevaEtiqueta();
            pilaSemantica.entrarBucle(lFin, lFin);  // break sale del switch

      label_17:
      while (true) {
        hijo = gramaticaCase(t.image, lFin);
n.agregarHijo(hijo);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case CASE:{
          ;
          break;
          }
        default:
          jj_la1[37] = jj_gen;
          break label_17;
        }
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case DEFAULT_TOKEN:{
        hijo = gramaticaDefault(lFin);
n.agregarHijo(hijo);
        break;
        }
      default:
        jj_la1[38] = jj_gen;
        ;
      }
      jj_consume_token(LLAVEDER);
pilaSemantica.emitirLabel(lFin);
            pilaSemantica.salirBucle();
            {if ("" != null) return n;}
    } catch (ParseException e) {
listaErroresSintacticos.add(manejarErrorSintactico(e));
        skipToNextBreakpoint(LLAVEDER, FIN, EOF);
        if (getToken(1).kind == LLAVEDER) getNextToken();
        {if ("" != null) return null;}
    }
    throw new Error("Missing return statement in function");
}

  static final public Nodo gramaticaCase(String varSwitch, String lFin) throws ParseException {Nodo n = new Nodo("Case"); Nodo v; Nodo hijo;
    String lSiguiente, tempCase;
    jj_consume_token(CASE);
    v = valor();
    jj_consume_token(DOS_PUNTOS);
lSiguiente = pilaSemantica.nuevaEtiqueta();
        tempCase   = pilaSemantica.nuevaTemporal();
        // Si var != caseVal  →  salta al siguiente case
        pilaSemantica.emitir("==", varSwitch, v.valor, tempCase);
        pilaSemantica.emitirSaltoCondicional(tempCase, lSiguiente);
    label_18:
    while (true) {
      hijo = Codigo();
n.agregarHijo(hijo);
      if (jj_2_9(2)) {
        ;
      } else {
        break label_18;
      }
    }
pilaSemantica.emitirSalto(lFin);       // sale del switch al terminar el cuerpo
        pilaSemantica.emitirLabel(lSiguiente); // entrada del siguiente case

    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case BREAK:{
      jj_consume_token(BREAK);
      jj_consume_token(DELIMITADOR);
      break;
      }
    default:
      jj_la1[39] = jj_gen;
      ;
    }
{if ("" != null) return n;}
    throw new Error("Missing return statement in function");
}

  static final public Nodo gramaticaDefault(String lFin) throws ParseException {Nodo n = new Nodo("Default"); Nodo hijo;
    jj_consume_token(DEFAULT_TOKEN);
    jj_consume_token(DOS_PUNTOS);
    label_19:
    while (true) {
      hijo = Codigo();
n.agregarHijo(hijo);
      if (jj_2_10(2)) {
        ;
      } else {
        break label_19;
      }
    }
pilaSemantica.emitirSalto(lFin);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case BREAK:{
      jj_consume_token(BREAK);
      jj_consume_token(DELIMITADOR);
      break;
      }
    default:
      jj_la1[40] = jj_gen;
      ;
    }
{if ("" != null) return n;}
    throw new Error("Missing return statement in function");
}

  static final public Nodo gramaticaTryCatch() throws ParseException {Nodo n = new Nodo("Try-Catch"); Nodo hijo; Token exTipo, exNom;
    try {
      jj_consume_token(TRY);
      jj_consume_token(LLAVEIZQ);
      label_20:
      while (true) {
        hijo = Codigo();
n.agregarHijo(hijo);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case FOR:
        case WHILE:
        case MATRIZ:
        case VECTOR:
        case SI:
        case SINO:
        case SWITCH:
        case BREAK:
        case CONTINUE:
        case TRY:
        case CATCH:
        case BOOL:
        case VAR:
        case CONST:
        case LEER:
        case ESCRIBIR:
        case VOID:
        case FUNC:
        case IDENTIFICADOR:{
          ;
          break;
          }
        default:
          jj_la1[41] = jj_gen;
          break label_20;
        }
      }
      jj_consume_token(LLAVEDER);
      label_21:
      while (true) {
        jj_consume_token(CATCH);
        jj_consume_token(PARENIZQ);
        exTipo = jj_consume_token(IDENTIFICADOR);
        exNom = jj_consume_token(IDENTIFICADOR);
        jj_consume_token(PARENDER);
        jj_consume_token(LLAVEIZQ);
Nodo c = new Nodo("Catch");
               c.agregarHijo(new Nodo("Excepcion: " + exTipo.image + " " + exNom.image));
               n.agregarHijo(c);
        label_22:
        while (true) {
          hijo = Codigo();
n.agregarHijo(hijo);
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case FOR:
          case WHILE:
          case MATRIZ:
          case VECTOR:
          case SI:
          case SINO:
          case SWITCH:
          case BREAK:
          case CONTINUE:
          case TRY:
          case CATCH:
          case BOOL:
          case VAR:
          case CONST:
          case LEER:
          case ESCRIBIR:
          case VOID:
          case FUNC:
          case IDENTIFICADOR:{
            ;
            break;
            }
          default:
            jj_la1[42] = jj_gen;
            break label_22;
          }
        }
        jj_consume_token(LLAVEDER);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case CATCH:{
          ;
          break;
          }
        default:
          jj_la1[43] = jj_gen;
          break label_21;
        }
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case FINALLY:{
        jj_consume_token(FINALLY);
        jj_consume_token(LLAVEIZQ);
Nodo f = new Nodo("Finally"); n.agregarHijo(f);
        label_23:
        while (true) {
          hijo = Codigo();
n.agregarHijo(hijo);
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case FOR:
          case WHILE:
          case MATRIZ:
          case VECTOR:
          case SI:
          case SINO:
          case SWITCH:
          case BREAK:
          case CONTINUE:
          case TRY:
          case CATCH:
          case BOOL:
          case VAR:
          case CONST:
          case LEER:
          case ESCRIBIR:
          case VOID:
          case FUNC:
          case IDENTIFICADOR:{
            ;
            break;
            }
          default:
            jj_la1[44] = jj_gen;
            break label_23;
          }
        }
        jj_consume_token(LLAVEDER);
        break;
        }
      default:
        jj_la1[45] = jj_gen;
        ;
      }
{if ("" != null) return n;}
    } catch (ParseException e) {
listaErroresSintacticos.add(manejarErrorSintactico(e));
        skipToNextBreakpoint(LLAVEDER, FIN, EOF);
        if (getToken(1).kind == LLAVEDER) getNextToken();
        {if ("" != null) return null;}
    }
    throw new Error("Missing return statement in function");
}

  static final public Nodo declararArreglo() throws ParseException {Token t; Nodo n; String tipo; Nodo init = null;
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case VECTOR:{
        jj_consume_token(VECTOR);
        t = jj_consume_token(IDENTIFICADOR);
        tipo = tipoDato();
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case CORCHIZQ:{
          jj_consume_token(CORCHIZQ);
          jj_consume_token(ENTEROS);
          jj_consume_token(CORCHDER);
          break;
          }
        case IGUAL:{
          jj_consume_token(IGUAL);
          init = inicializarArreglo(t.image, 0);
          break;
          }
        default:
          jj_la1[46] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
n = new Nodo("Vector: " + t.image, tipo); if(init != null) n.agregarHijo(init);
        break;
        }
      case MATRIZ:{
        jj_consume_token(MATRIZ);
        t = jj_consume_token(IDENTIFICADOR);
        tipo = tipoDato();
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case CORCHIZQ:{
          jj_consume_token(CORCHIZQ);
          jj_consume_token(ENTEROS);
          jj_consume_token(CORCHDER);
          jj_consume_token(CORCHIZQ);
          jj_consume_token(ENTEROS);
          jj_consume_token(CORCHDER);
          break;
          }
        case IGUAL:{
          jj_consume_token(IGUAL);
          init = inicializarMatriz(t.image);
          break;
          }
        default:
          jj_la1[47] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
n = new Nodo("Matriz: " + t.image, tipo); if(init != null) n.agregarHijo(init);
        break;
        }
      default:
        jj_la1[48] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(DELIMITADOR);
try { tablaSimbolos.insertar(t.image, "array_" + tipo); }
            catch(Exception e) { listaErroresSemanticos.add(e.getMessage()); }
            {if ("" != null) return n;}
    } catch (ParseException e) {
listaErroresSintacticos.add(manejarErrorSintactico(e));
        skipToNextBreakpoint(DELIMITADOR, LLAVEDER, FIN, EOF);
        if (getToken(1).kind == DELIMITADOR) getNextToken();
        {if ("" != null) return null;}
    }
    throw new Error("Missing return statement in function");
}

// 2.3.6 – inicializacion de arreglo con cuadruplos ([]=, val, idx, nombre)
  static final public Nodo inicializarArreglo(String arrayName, int startIdx) throws ParseException {Nodo n = new Nodo("Inicializacion Arreglo"); Nodo v; int idx = startIdx;
    jj_consume_token(CORCHIZQ);
    v = valor();
n.agregarHijo(v); pilaSemantica.emitir("[]=", v.valor, String.valueOf(idx++), arrayName);
    label_24:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case COMA:{
        ;
        break;
        }
      default:
        jj_la1[49] = jj_gen;
        break label_24;
      }
      jj_consume_token(COMA);
      v = valor();
n.agregarHijo(v); pilaSemantica.emitir("[]=", v.valor, String.valueOf(idx++), arrayName);
    }
    jj_consume_token(CORCHDER);
{if ("" != null) return n;}
    throw new Error("Missing return statement in function");
}

// 2.3.6 – inicializacion de matriz con indice plano por fila
  static final public Nodo inicializarMatriz(String arrayName) throws ParseException {Nodo n = new Nodo("Inicializacion Matriz"); Nodo fila; int flatIdx = 0;
    jj_consume_token(CORCHIZQ);
    fila = inicializarArreglo(arrayName, flatIdx);
n.agregarHijo(fila); flatIdx += fila.hijos.size();
    label_25:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case COMA:{
        ;
        break;
        }
      default:
        jj_la1[50] = jj_gen;
        break label_25;
      }
      jj_consume_token(COMA);
      fila = inicializarArreglo(arrayName, flatIdx);
n.agregarHijo(fila); flatIdx += fila.hijos.size();
    }
    jj_consume_token(CORCHDER);
{if ("" != null) return n;}
    throw new Error("Missing return statement in function");
}

  static private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_1()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_2_2(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_2()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  static private boolean jj_2_3(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_3()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  static private boolean jj_2_4(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_4()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  static private boolean jj_2_5(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_5()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  static private boolean jj_2_6(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_6()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  static private boolean jj_2_7(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_7()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  static private boolean jj_2_8(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_8()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  static private boolean jj_2_9(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_9()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  static private boolean jj_2_10(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_10()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  static private boolean jj_3R_Codigo_363_15_44()
 {
    if (jj_scan_token(CONTINUE)) return true;
    if (jj_scan_token(DELIMITADOR)) return true;
    return false;
  }

  static private boolean jj_3_7()
 {
    if (jj_3R_gramaticaTryCatch_1059_5_32()) return true;
    return false;
  }

  static private boolean jj_3_6()
 {
    if (jj_3R_gramaticaSwitch_999_5_31()) return true;
    return false;
  }

  static private boolean jj_3R_Codigo_360_15_43()
 {
    if (jj_3R_SentenciasFunciones_858_5_55()) return true;
    return false;
  }

  static private boolean jj_3R_Codigo_359_15_42()
 {
    if (jj_3R_gramaticaOperadorLogico_768_5_54()) return true;
    return false;
  }

  static private boolean jj_3R_tipoDato_461_7_64()
 {
    if (jj_scan_token(STRING)) return true;
    return false;
  }

  static private boolean jj_3_5()
 {
    if (jj_3R_gramaticaFor_807_5_30()) return true;
    return false;
  }

  static private boolean jj_3R_tipoDato_460_7_63()
 {
    if (jj_scan_token(BOOL)) return true;
    return false;
  }

  static private boolean jj_3_4()
 {
    if (jj_3R_llamarFuncion_947_5_29()) return true;
    return false;
  }

  static private boolean jj_3R_tipoDato_459_7_62()
 {
    if (jj_scan_token(FLOAT)) return true;
    return false;
  }

  static private boolean jj_3_3()
 {
    if (jj_3R_gramaticaAsignacion_666_5_28()) return true;
    return false;
  }

  static private boolean jj_3_2()
 {
    if (jj_3R_gramaticaWhile_636_5_27()) return true;
    return false;
  }

  static private boolean jj_3_1()
 {
    if (jj_3R_gramaticaSi_542_5_26()) return true;
    return false;
  }

  static private boolean jj_3R_tipoDato_458_5_61()
 {
    if (jj_scan_token(INT)) return true;
    return false;
  }

  static private boolean jj_3R_tipoDato_458_5_60()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_tipoDato_458_5_61()) {
    jj_scanpos = xsp;
    if (jj_3R_tipoDato_459_7_62()) {
    jj_scanpos = xsp;
    if (jj_3R_tipoDato_460_7_63()) {
    jj_scanpos = xsp;
    if (jj_3R_tipoDato_461_7_64()) return true;
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_Codigo_353_15_41()
 {
    if (jj_3R_gramaticaLeer_525_5_53()) return true;
    return false;
  }

  static private boolean jj_3R_Codigo_352_15_40()
 {
    if (jj_3R_gramaticaEscribir_507_5_52()) return true;
    return false;
  }

  static private boolean jj_3R_Codigo_351_15_39()
 {
    if (jj_3R_declararConstante_431_5_51()) return true;
    return false;
  }

  static private boolean jj_3R_Codigo_350_15_38()
 {
    if (jj_3R_declararArreglo_1086_5_50()) return true;
    return false;
  }

  static private boolean jj_3R_Codigo_349_15_37()
 {
    if (jj_3R_declararVariable_407_5_49()) return true;
    return false;
  }

  static private boolean jj_3R_gramaticaSi_542_5_26()
 {
    if (jj_scan_token(SI)) return true;
    if (jj_scan_token(PARENIZQ)) return true;
    return false;
  }

  static private boolean jj_3R_gramaticaWhile_636_5_27()
 {
    if (jj_scan_token(WHILE)) return true;
    if (jj_scan_token(PARENIZQ)) return true;
    return false;
  }

  static private boolean jj_3R_Codigo_347_5_33()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_Codigo_349_15_37()) {
    jj_scanpos = xsp;
    if (jj_3R_Codigo_350_15_38()) {
    jj_scanpos = xsp;
    if (jj_3R_Codigo_351_15_39()) {
    jj_scanpos = xsp;
    if (jj_3R_Codigo_352_15_40()) {
    jj_scanpos = xsp;
    if (jj_3R_Codigo_353_15_41()) {
    jj_scanpos = xsp;
    if (jj_3_1()) {
    jj_scanpos = xsp;
    if (jj_3_2()) {
    jj_scanpos = xsp;
    if (jj_3_3()) {
    jj_scanpos = xsp;
    if (jj_3_4()) {
    jj_scanpos = xsp;
    if (jj_3_5()) {
    jj_scanpos = xsp;
    if (jj_3R_Codigo_359_15_42()) {
    jj_scanpos = xsp;
    if (jj_3R_Codigo_360_15_43()) {
    jj_scanpos = xsp;
    if (jj_3_6()) {
    jj_scanpos = xsp;
    if (jj_3_7()) {
    jj_scanpos = xsp;
    if (jj_3R_Codigo_363_15_44()) {
    jj_scanpos = xsp;
    if (jj_3R_Codigo_368_15_45()) {
    jj_scanpos = xsp;
    if (jj_3R_Codigo_373_15_46()) {
    jj_scanpos = xsp;
    if (jj_3R_Codigo_380_15_47()) {
    jj_scanpos = xsp;
    if (jj_3R_Codigo_387_15_48()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_declararArreglo_1096_13_57()
 {
    if (jj_scan_token(MATRIZ)) return true;
    if (jj_scan_token(IDENTIFICADOR)) return true;
    return false;
  }

  static private boolean jj_3R_declararArreglo_1088_13_56()
 {
    if (jj_scan_token(VECTOR)) return true;
    if (jj_scan_token(IDENTIFICADOR)) return true;
    return false;
  }

  static private boolean jj_3R_declararConstante_431_5_51()
 {
    if (jj_scan_token(CONST)) return true;
    if (jj_scan_token(IDENTIFICADOR)) return true;
    return false;
  }

  static private boolean jj_3R_gramaticaLeer_525_5_53()
 {
    if (jj_scan_token(LEER)) return true;
    if (jj_scan_token(PARENIZQ)) return true;
    return false;
  }

  static private boolean jj_3R_gramaticaSwitch_999_5_31()
 {
    if (jj_scan_token(SWITCH)) return true;
    if (jj_scan_token(PARENIZQ)) return true;
    return false;
  }

  static private boolean jj_3R_gramaticaFor_807_5_30()
 {
    if (jj_scan_token(FOR)) return true;
    if (jj_scan_token(PARENIZQ)) return true;
    return false;
  }

  static private boolean jj_3R_declararArreglo_1086_5_50()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_declararArreglo_1088_13_56()) {
    jj_scanpos = xsp;
    if (jj_3R_declararArreglo_1096_13_57()) return true;
    }
    return false;
  }

  static private boolean jj_3R_SentenciasFunciones_890_9_59()
 {
    if (jj_scan_token(VOID)) return true;
    if (jj_scan_token(IDENTIFICADOR)) return true;
    return false;
  }

  static private boolean jj_3R_gramaticaEscribir_507_5_52()
 {
    if (jj_scan_token(ESCRIBIR)) return true;
    if (jj_scan_token(PARENIZQ)) return true;
    return false;
  }

  static private boolean jj_3R_declararVariable_407_5_49()
 {
    if (jj_scan_token(VAR)) return true;
    if (jj_scan_token(IDENTIFICADOR)) return true;
    return false;
  }

  static private boolean jj_3R_Codigo_387_15_48()
 {
    if (jj_scan_token(IDENTIFICADOR)) return true;
    return false;
  }

  static private boolean jj_3R_gramaticaAsignacion_676_11_36()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(44)) {
    jj_scanpos = xsp;
    if (jj_scan_token(45)) {
    jj_scanpos = xsp;
    if (jj_scan_token(46)) {
    jj_scanpos = xsp;
    if (jj_scan_token(47)) return true;
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_gramaticaAsignacion_673_11_35()
 {
    if (jj_scan_token(IGUAL)) return true;
    return false;
  }

  static private boolean jj_3R_gramaticaTryCatch_1059_5_32()
 {
    if (jj_scan_token(TRY)) return true;
    if (jj_scan_token(LLAVEIZQ)) return true;
    return false;
  }

  static private boolean jj_3_8()
 {
    if (jj_scan_token(IDENTIFICADOR)) return true;
    if (jj_scan_token(CORCHIZQ)) return true;
    return false;
  }

  static private boolean jj_3R_gramaticaAsignacion_670_11_34()
 {
    if (jj_scan_token(CORCHIZQ)) return true;
    return false;
  }

  static private boolean jj_3R_Codigo_380_15_47()
 {
    if (jj_scan_token(CATCH)) return true;
    return false;
  }

  static private boolean jj_3R_SentenciasFunciones_859_9_58()
 {
    if (jj_scan_token(FUNC)) return true;
    if (jj_3R_tipoDato_458_5_60()) return true;
    return false;
  }

  static private boolean jj_3R_gramaticaOperadorLogico_768_5_54()
 {
    if (jj_scan_token(BOOL)) return true;
    if (jj_scan_token(IDENTIFICADOR)) return true;
    return false;
  }

  static private boolean jj_3_10()
 {
    if (jj_3R_Codigo_347_5_33()) return true;
    return false;
  }

  static private boolean jj_3R_SentenciasFunciones_858_5_55()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_SentenciasFunciones_859_9_58()) {
    jj_scanpos = xsp;
    if (jj_3R_SentenciasFunciones_890_9_59()) return true;
    }
    return false;
  }

  static private boolean jj_3R_Codigo_373_15_46()
 {
    if (jj_scan_token(SINO)) return true;
    return false;
  }

  static private boolean jj_3R_gramaticaAsignacion_666_5_28()
 {
    if (jj_scan_token(IDENTIFICADOR)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_gramaticaAsignacion_670_11_34()) {
    jj_scanpos = xsp;
    if (jj_3R_gramaticaAsignacion_673_11_35()) {
    jj_scanpos = xsp;
    if (jj_3R_gramaticaAsignacion_676_11_36()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_Codigo_368_15_45()
 {
    if (jj_scan_token(BREAK)) return true;
    if (jj_scan_token(DELIMITADOR)) return true;
    return false;
  }

  static private boolean jj_3R_llamarFuncion_947_5_29()
 {
    if (jj_scan_token(FUNC)) return true;
    if (jj_scan_token(IDENTIFICADOR)) return true;
    if (jj_scan_token(PARENIZQ)) return true;
    return false;
  }

  static private boolean jj_3_9()
 {
    if (jj_3R_Codigo_347_5_33()) return true;
    return false;
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public AnalizadorAqheranTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[51];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	   jj_la1_init_2();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x68f3f80,0x6000600,0x800000,0xb1000,0x1e00000,0x0,0x0,0x0,0x0,0x0,0x0,0x68f3f80,0x1000,0x68f3f80,0x0,0x0,0x0,0x68f3f80,0x0,0x0,0x0,0x18000000,0x18000000,0xe0000000,0xe0000000,0x68f3f80,0x0,0x0,0x68f3f80,0x0,0x68f3f80,0x0,0x0,0x0,0x0,0x0,0x0,0x4000,0x8000,0x10000,0x10000,0x68f3f80,0x68f3f80,0x80000,0x68f3f80,0x100000,0x0,0x0,0x600,0x0,0x0,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x81800000,0x1800000,0x0,0x0,0x0,0x7f0000,0x0,0x80000,0x0,0x80000,0x80000,0x1800000,0x0,0x1800000,0x1c,0x1c,0xfa0,0x1800000,0x7f0000,0xf000,0x1000f040,0x0,0x0,0x0,0x0,0x1800000,0x3,0x0,0x1800000,0x0,0x1800000,0x0,0x8000000,0x8000000,0x7f0000,0x8000000,0x7f0000,0x0,0x0,0x0,0x0,0x1800000,0x1800000,0x0,0x1800000,0x0,0x10000040,0x10000040,0x0,0x8000000,0x8000000,};
	}
	private static void jj_la1_init_2() {
	   jj_la1_2 = new int[] {0x310,0x0,0x110,0x200,0x0,0x1,0x200,0x200,0x4,0x200,0x200,0x310,0x0,0x310,0x0,0x0,0x0,0x310,0x301,0x0,0x0,0x0,0x0,0x0,0x0,0x310,0x0,0x200,0x310,0x200,0x310,0x110,0x0,0x0,0x201,0x0,0x201,0x0,0x0,0x0,0x0,0x310,0x310,0x0,0x310,0x0,0x0,0x0,0x0,0x0,0x0,};
	}
  static final private JJCalls[] jj_2_rtns = new JJCalls[10];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  /** Constructor with InputStream. */
  public AnalizadorAqheran(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public AnalizadorAqheran(java.io.InputStream stream, String encoding) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser.  ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new AnalizadorAqheranTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 51; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 51; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public AnalizadorAqheran(java.io.Reader stream) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new AnalizadorAqheranTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 51; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new AnalizadorAqheranTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 51; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public AnalizadorAqheran(AnalizadorAqheranTokenManager tm) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 51; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(AnalizadorAqheranTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 51; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   if (++jj_gc > 100) {
		 jj_gc = 0;
		 for (int i = 0; i < jj_2_rtns.length; i++) {
		   JJCalls c = jj_2_rtns[i];
		   while (c != null) {
			 if (c.gen < jj_gen) c.first = null;
			 c = c.next;
		   }
		 }
	   }
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error {
    @Override
    public Throwable fillInStackTrace() {
      return this;
    }
  }
  static private final LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
	 if (jj_scanpos == jj_lastpos) {
	   jj_la--;
	   if (jj_scanpos.next == null) {
		 jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
	   } else {
		 jj_lastpos = jj_scanpos = jj_scanpos.next;
	   }
	 } else {
	   jj_scanpos = jj_scanpos.next;
	 }
	 if (jj_rescan) {
	   int i = 0; Token tok = token;
	   while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
	   if (tok != null) jj_add_error_token(kind, i);
	 }
	 if (jj_scanpos.kind != kind) return true;
	 if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
	 return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  static private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
	 if (pos >= 100) {
		return;
	 }

	 if (pos == jj_endpos + 1) {
	   jj_lasttokens[jj_endpos++] = kind;
	 } else if (jj_endpos != 0) {
	   jj_expentry = new int[jj_endpos];

	   for (int i = 0; i < jj_endpos; i++) {
		 jj_expentry[i] = jj_lasttokens[i];
	   }

	   for (int[] oldentry : jj_expentries) {
		 if (oldentry.length == jj_expentry.length) {
		   boolean isMatched = true;

		   for (int i = 0; i < jj_expentry.length; i++) {
			 if (oldentry[i] != jj_expentry[i]) {
			   isMatched = false;
			   break;
			 }

		   }
		   if (isMatched) {
			 jj_expentries.add(jj_expentry);
			 break;
		   }
		 }
	   }

	   if (pos != 0) {
		 jj_lasttokens[(jj_endpos = pos) - 1] = kind;
	   }
	 }
  }

  /** Generate ParseException. */
  static public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[75];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 51; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		   if ((jj_la1_2[i] & (1<<j)) != 0) {
			 la1tokens[64+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 75; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 jj_endpos = 0;
	 jj_rescan_token();
	 jj_add_error_token(0, 0);
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  static private boolean trace_enabled;

/** Trace enabled. */
  static final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

  static private void jj_rescan_token() {
	 jj_rescan = true;
	 for (int i = 0; i < 10; i++) {
	   try {
		 JJCalls p = jj_2_rtns[i];

		 do {
		   if (p.gen > jj_gen) {
			 jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
			 switch (i) {
			   case 0: jj_3_1(); break;
			   case 1: jj_3_2(); break;
			   case 2: jj_3_3(); break;
			   case 3: jj_3_4(); break;
			   case 4: jj_3_5(); break;
			   case 5: jj_3_6(); break;
			   case 6: jj_3_7(); break;
			   case 7: jj_3_8(); break;
			   case 8: jj_3_9(); break;
			   case 9: jj_3_10(); break;
			 }
		   }
		   p = p.next;
		 } while (p != null);

		 } catch(LookaheadSuccess ls) { }
	 }
	 jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
	 JJCalls p = jj_2_rtns[index];
	 while (p.gen > jj_gen) {
	   if (p.next == null) { p = p.next = new JJCalls(); break; }
	   p = p.next;
	 }

	 p.gen = jj_gen + xla - jj_la; 
	 p.first = token;
	 p.arg = xla;
  }

  static final class JJCalls {
	 int gen;
	 Token first;
	 int arg;
	 JJCalls next;
  }

}
