/* Generated By:JavaCC: Do not edit this line. AnalizadorAqheranConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalizadorAqheranConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INT = 7;
  /** RegularExpression Id. */
  int FLOAT = 8;
  /** RegularExpression Id. */
  int BOOL = 9;
  /** RegularExpression Id. */
  int STRING = 10;
  /** RegularExpression Id. */
  int VAR = 11;
  /** RegularExpression Id. */
  int CONST = 12;
  /** RegularExpression Id. */
  int MAS = 13;
  /** RegularExpression Id. */
  int MENOS = 14;
  /** RegularExpression Id. */
  int MULT = 15;
  /** RegularExpression Id. */
  int DIV = 16;
  /** RegularExpression Id. */
  int MOD = 17;
  /** RegularExpression Id. */
  int INC = 18;
  /** RegularExpression Id. */
  int DEC = 19;
  /** RegularExpression Id. */
  int AND = 20;
  /** RegularExpression Id. */
  int OR = 21;
  /** RegularExpression Id. */
  int NOT = 22;
  /** RegularExpression Id. */
  int IGUALDAD = 23;
  /** RegularExpression Id. */
  int IGUAL = 24;
  /** RegularExpression Id. */
  int DESIGUALDAD = 25;
  /** RegularExpression Id. */
  int MAYOR = 26;
  /** RegularExpression Id. */
  int MENOR = 27;
  /** RegularExpression Id. */
  int MAYORIGUAL = 28;
  /** RegularExpression Id. */
  int MENORIGUAL = 29;
  /** RegularExpression Id. */
  int ASIG_SUMA = 30;
  /** RegularExpression Id. */
  int ASIG_RESTA = 31;
  /** RegularExpression Id. */
  int ASIG_MULT = 32;
  /** RegularExpression Id. */
  int ASIG_DIV = 33;
  /** RegularExpression Id. */
  int ENTEROS = 34;
  /** RegularExpression Id. */
  int NUMERODECIMAL = 35;
  /** RegularExpression Id. */
  int HEX_LITERAL = 36;
  /** RegularExpression Id. */
  int VCAD = 37;
  /** RegularExpression Id. */
  int TRUE = 38;
  /** RegularExpression Id. */
  int FALSE = 39;
  /** RegularExpression Id. */
  int NULL = 40;
  /** RegularExpression Id. */
  int FOR = 41;
  /** RegularExpression Id. */
  int WHILE = 42;
  /** RegularExpression Id. */
  int MATRIZ = 43;
  /** RegularExpression Id. */
  int VECTOR = 44;
  /** RegularExpression Id. */
  int SI = 45;
  /** RegularExpression Id. */
  int SINO = 46;
  /** RegularExpression Id. */
  int SWITCH = 47;
  /** RegularExpression Id. */
  int CASE = 48;
  /** RegularExpression Id. */
  int DEFAULT_TOKEN = 49;
  /** RegularExpression Id. */
  int BREAK = 50;
  /** RegularExpression Id. */
  int CONTINUE = 51;
  /** RegularExpression Id. */
  int TRY = 52;
  /** RegularExpression Id. */
  int CATCH = 53;
  /** RegularExpression Id. */
  int FINALLY = 54;
  /** RegularExpression Id. */
  int LEER = 55;
  /** RegularExpression Id. */
  int ESCRIBIR = 56;
  /** RegularExpression Id. */
  int PUNTO = 57;
  /** RegularExpression Id. */
  int DELIMITADOR = 58;
  /** RegularExpression Id. */
  int COMA = 59;
  /** RegularExpression Id. */
  int CORCHIZQ = 60;
  /** RegularExpression Id. */
  int CORCHDER = 61;
  /** RegularExpression Id. */
  int LLAVEIZQ = 62;
  /** RegularExpression Id. */
  int LLAVEDER = 63;
  /** RegularExpression Id. */
  int PARENIZQ = 64;
  /** RegularExpression Id. */
  int PARENDER = 65;
  /** RegularExpression Id. */
  int CONCATENAR = 66;
  /** RegularExpression Id. */
  int DOS_PUNTOS = 67;
  /** RegularExpression Id. */
  int VOID = 68;
  /** RegularExpression Id. */
  int RETURN = 69;
  /** RegularExpression Id. */
  int INICIO = 70;
  /** RegularExpression Id. */
  int FIN = 71;
  /** RegularExpression Id. */
  int FUNC = 72;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 73;
  /** RegularExpression Id. */
  int ERROR = 74;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"int\"",
    "\"float\"",
    "\"bool\"",
    "\"string\"",
    "\"@\"",
    "\"#\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"++\"",
    "\"--\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"==\"",
    "\"=\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "<ENTEROS>",
    "<NUMERODECIMAL>",
    "<HEX_LITERAL>",
    "<VCAD>",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "\"for\"",
    "\"while\"",
    "\"matrix\"",
    "\"vec\"",
    "\"if\"",
    "\"else\"",
    "\"switch\"",
    "\"case\"",
    "\"default\"",
    "\"break\"",
    "\"continue\"",
    "\"try\"",
    "\"catch\"",
    "\"finally\"",
    "\"readline\"",
    "<ESCRIBIR>",
    "\".\"",
    "\";\"",
    "\",\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"&\"",
    "\":\"",
    "\"void\"",
    "\"return\"",
    "\"start\"",
    "\"end\"",
    "\"fn\"",
    "<IDENTIFICADOR>",
    "<ERROR>",
  };

}
