/* AnalizadorAqheran.java */
/* Generated By:JavaCC: Do not edit this line. AnalizadorAqheran.java */
import java.io.*;
import java.util.ArrayList;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.charset.StandardCharsets;

public class AnalizadorAqheran implements AnalizadorAqheranConstants {

    // Array que guarda los Errores Sintacticos recuperados
    static ArrayList<String> tabla = new ArrayList<String>();

    public static void main(String[] args) {
        try {
            // -- CODIGO DE PRUEBA DURO (HARDCODED) --
            // Esto evita problemas de lectura de archivos en Windows (UTF-16 vs UTF-8)
            String contenido = new String(Files.readAllBytes(Paths.get(args[0])), StandardCharsets.UTF_8);
            System.out.println("--- Contenido del archivo: " + args[0] + " ---");
            System.out.println(contenido);
            System.out.println("----------------------------------------");

            // Limpieza de BOM para Windows
            if (contenido.startsWith("\ufeff")) {
                contenido = contenido.substring(1);
            }

            System.out.println("--- Analizando Codigo de Prueba ---");
            System.out.println(contenido);
            System.out.println("-----------------------------------");

            AnalizadorAqheran parser = new AnalizadorAqheran(new StringReader(contenido));
            parser.parse();

        } catch (Exception e) {
            System.out.println(e.getMessage());
            e.printStackTrace();
        }
    }

    // Metodo principal que ejecuta analisis lexico y luego sintactico
    public void parse() throws IOException {
        Token token;
        // Referencia a los errores lexicos del TokenManager
        ArrayList<String> erroresLexicos = AnalizadorAqheranTokenManager.tablaErrores;

        boolean seEncontraronErroresLexicos = false;

        // Ciclo de Analisis Lexico (Consumir todos los tokens para buscar errores lexicos)
        // Nota: En un compilador real, el parser consume tokens bajo demanda. 
        // Aqui lo recorremos primero solo para reportar errores lexicos por separado si se desea,
        // o podemos dejar que el parser sintactico guíe el consumo.
        // *Para mantener el estilo de tu archivo original, dejamos que el parser sintactico haga el trabajo,
        // pero verificamos errores lexicos al final si el TokenManager los guardó.*

        try {
            principal();

            // Reporte final
            if (!erroresLexicos.isEmpty()) {
                System.out.println("\n** Errores LEXICOS encontrados: **");
                for (String err : erroresLexicos) System.out.println(err);
            } else {
                System.out.println("\n** Analisis LEXICO sin errores. **");
            }

            if (!tabla.isEmpty()) {
                System.out.println("\n** Errores SINTACTICOS encontrados: **");
                for (String err : tabla) System.out.println(err);
            } else {
                System.out.println("\n** Analisis SINTACTICO sin errores. **");
            }

        } catch (ParseException e) {
            tabla.add(manejarErrorSintactico(e));
        }
    }

    static String manejarErrorSintactico(ParseException e) {
        String mensajeOriginal = e.getMessage();
        // Traduccion simple para el usuario
        String mensajeTraducido = mensajeOriginal
            .replace("Encountered", "Encontrado")
            .replace("at line", "en la l\u00ednea")
            .replace("column", "columna")
            .replace("Was expecting:", "Se esperaba:")
            .replace("Was expecting one of:", "Se espera una de estas opciones:");

        return "Error Sintactico: " + mensajeTraducido;
    }

// ==========================================
// ANALISIS SINTACTICO
// ==========================================
  static final public 
void principal() throws ParseException {
    try {
      jj_consume_token(INICIO);
      jj_consume_token(IDENTIFICADOR);
      jj_consume_token(LLAVEIZQ);
      label_1:
      while (true) {
        Codigo();
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case BOOL:
        case VAR:
        case CONST:
        case FOR:
        case WHILE:
        case SI:
        case LEER:
        case ESCRIBIR:
        case VOID:
        case FUNC:
        case IDENTIFICADOR:{
          ;
          break;
          }
        default:
          jj_la1[0] = jj_gen;
          break label_1;
        }
      }
      jj_consume_token(LLAVEDER);
      jj_consume_token(FIN);
    } catch (ParseException e) {
tabla.add(manejarErrorSintactico(e));
        // Recuperacion basica: consumir hasta el fin
        Token t;
        do {
            t = getNextToken();
        } while (t.kind != EOF && t.kind != FIN);
    }
}

  static final public void Codigo() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case VAR:{
      declararVariable();
      break;
      }
    case CONST:{
      declararConstante();
      break;
      }
    case ESCRIBIR:{
      gramaticaEscribir();
      break;
      }
    case LEER:{
      gramaticaLeer();
      break;
      }
    case SI:{
      gramaticaSi();
      break;
      }
    case WHILE:{
      gramaticaWhile();
      break;
      }
    case IDENTIFICADOR:{
      gramaticaAsignacion();
      break;
      }
    case FUNC:{
      llamarFuncion();
      break;
      }
    case FOR:{
      gramaticaFor();
      break;
      }
    case BOOL:{
      gramaticaOperadorLogico();
      break;
      }
    case VOID:{
      SentenciasFunciones();
      break;
      }
    default:
      jj_la1[1] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  static final public void declararVariable() throws ParseException {
    try {
      jj_consume_token(VAR);
      jj_consume_token(IDENTIFICADOR);
      tipoDato();
      jj_consume_token(DELIMITADOR);
    } catch (ParseException e) {
tabla.add(manejarErrorSintactico(e));
    }
}

  static final public void declararConstante() throws ParseException {
    try {
      jj_consume_token(CONST);
      jj_consume_token(IDENTIFICADOR);
      tipoDato();
      jj_consume_token(IGUAL);
      valor();
      jj_consume_token(DELIMITADOR);
    } catch (ParseException e) {
tabla.add(manejarErrorSintactico(e));
    }
}

  static final public void tipoDato() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INT:{
      jj_consume_token(INT);
      break;
      }
    case FLOAT:{
      jj_consume_token(FLOAT);
      break;
      }
    case BOOL:{
      jj_consume_token(BOOL);
      break;
      }
    case STRING:{
      jj_consume_token(STRING);
      break;
      }
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

// Regla unificada para valores (enteros, decimales, cadenas, ids)
  static final public void valor() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ENTEROS:{
      jj_consume_token(ENTEROS);
      break;
      }
    case VCAD:{
      jj_consume_token(VCAD);
      break;
      }
    case NUMERODECIMAL:{
      jj_consume_token(NUMERODECIMAL);
      break;
      }
    case IDENTIFICADOR:{
      jj_consume_token(IDENTIFICADOR);
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  static final public void gramaticaEscribir() throws ParseException {
    try {
      jj_consume_token(ESCRIBIR);
      jj_consume_token(PARENIZQ);
      label_2:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case VCAD:{
          jj_consume_token(VCAD);
          break;
          }
        case IDENTIFICADOR:{
          jj_consume_token(IDENTIFICADOR);
          break;
          }
        default:
          jj_la1[4] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        label_3:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case CONCATENAR:{
            ;
            break;
            }
          default:
            jj_la1[5] = jj_gen;
            break label_3;
          }
          jj_consume_token(CONCATENAR);
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case VCAD:{
            jj_consume_token(VCAD);
            break;
            }
          case IDENTIFICADOR:{
            jj_consume_token(IDENTIFICADOR);
            break;
            }
          default:
            jj_la1[6] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
        }
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case VCAD:
        case IDENTIFICADOR:{
          ;
          break;
          }
        default:
          jj_la1[7] = jj_gen;
          break label_2;
        }
      }
      jj_consume_token(PARENDER);
      jj_consume_token(DELIMITADOR);
    } catch (ParseException e) {
tabla.add(manejarErrorSintactico(e));
    }
}

  static final public void gramaticaLeer() throws ParseException {
    try {
      jj_consume_token(LEER);
      jj_consume_token(PARENIZQ);
      jj_consume_token(IDENTIFICADOR);
      jj_consume_token(PARENDER);
      jj_consume_token(DELIMITADOR);
    } catch (ParseException e) {
tabla.add(manejarErrorSintactico(e));
    }
}

  static final public void gramaticaSi() throws ParseException {
    try {
      jj_consume_token(SI);
      jj_consume_token(PARENIZQ);
      condicion();
      jj_consume_token(PARENDER);
      jj_consume_token(LLAVEIZQ);
      label_4:
      while (true) {
        Codigo();
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case BOOL:
        case VAR:
        case CONST:
        case FOR:
        case WHILE:
        case SI:
        case LEER:
        case ESCRIBIR:
        case VOID:
        case FUNC:
        case IDENTIFICADOR:{
          ;
          break;
          }
        default:
          jj_la1[8] = jj_gen;
          break label_4;
        }
      }
      jj_consume_token(LLAVEDER);
      label_5:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case SINO:{
          ;
          break;
          }
        default:
          jj_la1[9] = jj_gen;
          break label_5;
        }
        gramaticaSiNo();
      }
    } catch (ParseException e) {
tabla.add(manejarErrorSintactico(e));
    }
}

  static final public void gramaticaSiNo() throws ParseException {
    try {
      jj_consume_token(SINO);
      jj_consume_token(LLAVEIZQ);
      label_6:
      while (true) {
        Codigo();
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case BOOL:
        case VAR:
        case CONST:
        case FOR:
        case WHILE:
        case SI:
        case LEER:
        case ESCRIBIR:
        case VOID:
        case FUNC:
        case IDENTIFICADOR:{
          ;
          break;
          }
        default:
          jj_la1[10] = jj_gen;
          break label_6;
        }
      }
      jj_consume_token(LLAVEDER);
    } catch (ParseException e) {
tabla.add(manejarErrorSintactico(e));
    }
}

  static final public void condicion() throws ParseException {
    try {
      valor();
      OperadoresComparadores();
      valor();
      label_7:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case AND:
        case OR:
        case NOT:{
          ;
          break;
          }
        default:
          jj_la1[11] = jj_gen;
          break label_7;
        }
        condicionLogicos();
      }
    } catch (ParseException e) {
tabla.add(manejarErrorSintactico(e));
    }
}

  static final public void condicionLogicos() throws ParseException {
    try {
      OperadoresLogicos();
      valor();
      OperadoresComparadores();
      valor();
    } catch (ParseException e) {
tabla.add(manejarErrorSintactico(e));
    }
}

  static final public void OperadoresLogicos() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case AND:{
      jj_consume_token(AND);
      break;
      }
    case OR:{
      jj_consume_token(OR);
      break;
      }
    case NOT:{
      jj_consume_token(NOT);
      break;
      }
    default:
      jj_la1[12] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  static final public void OperadoresComparadores() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IGUALDAD:{
      jj_consume_token(IGUALDAD);
      break;
      }
    case DESIGUALDAD:{
      jj_consume_token(DESIGUALDAD);
      break;
      }
    case MAYOR:{
      jj_consume_token(MAYOR);
      break;
      }
    case MENOR:{
      jj_consume_token(MENOR);
      break;
      }
    case MAYORIGUAL:{
      jj_consume_token(MAYORIGUAL);
      break;
      }
    case MENORIGUAL:{
      jj_consume_token(MENORIGUAL);
      break;
      }
    default:
      jj_la1[13] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  static final public void gramaticaWhile() throws ParseException {
    try {
      jj_consume_token(WHILE);
      jj_consume_token(PARENIZQ);
      condicion();
      jj_consume_token(PARENDER);
      jj_consume_token(LLAVEIZQ);
      label_8:
      while (true) {
        Codigo();
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case BOOL:
        case VAR:
        case CONST:
        case FOR:
        case WHILE:
        case SI:
        case LEER:
        case ESCRIBIR:
        case VOID:
        case FUNC:
        case IDENTIFICADOR:{
          ;
          break;
          }
        default:
          jj_la1[14] = jj_gen;
          break label_8;
        }
      }
      jj_consume_token(LLAVEDER);
    } catch (ParseException e) {
tabla.add(manejarErrorSintactico(e));
    }
}

  static final public void gramaticaAsignacion() throws ParseException {
    try {
      jj_consume_token(IDENTIFICADOR);
      jj_consume_token(IGUAL);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ENTEROS:
      case NUMERODECIMAL:
      case VCAD:
      case IDENTIFICADOR:{
        operacionSimple();
        break;
        }
      case FUNC:{
        asignacionConFuncion();
        break;
        }
      default:
        jj_la1[15] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(DELIMITADOR);
    } catch (ParseException e) {
tabla.add(manejarErrorSintactico(e));
    }
}

  static final public void operacionSimple() throws ParseException {
    try {
      label_9:
      while (true) {
        valor();
        label_10:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case MAS:
          case MENOS:
          case MULT:
          case DIV:
          case MOD:{
            ;
            break;
            }
          default:
            jj_la1[16] = jj_gen;
            break label_10;
          }
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case MAS:{
            jj_consume_token(MAS);
            break;
            }
          case MENOS:{
            jj_consume_token(MENOS);
            break;
            }
          case MULT:{
            jj_consume_token(MULT);
            break;
            }
          case DIV:{
            jj_consume_token(DIV);
            break;
            }
          case MOD:{
            jj_consume_token(MOD);
            break;
            }
          default:
            jj_la1[17] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
          valor();
        }
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case ENTEROS:
        case NUMERODECIMAL:
        case VCAD:
        case IDENTIFICADOR:{
          ;
          break;
          }
        default:
          jj_la1[18] = jj_gen;
          break label_9;
        }
      }
    } catch (ParseException e) {
tabla.add(manejarErrorSintactico(e));
    }
}

  static final public void gramaticaOperadorLogico() throws ParseException {
    try {
      jj_consume_token(BOOL);
      jj_consume_token(IDENTIFICADOR);
      jj_consume_token(IGUAL);
      condicionLogico();
      jj_consume_token(DELIMITADOR);
    } catch (ParseException e) {
tabla.add(manejarErrorSintactico(e));
    }
}

  static final public void condicionLogico() throws ParseException {
    try {
      valor();
      OperadoresLogicos();
      valor();
    } catch (ParseException e) {
tabla.add(manejarErrorSintactico(e));
    }
}

  static final public void gramaticaFor() throws ParseException {
    try {
      jj_consume_token(FOR);
      jj_consume_token(PARENIZQ);
      condicionFor();
      jj_consume_token(PARENDER);
      jj_consume_token(LLAVEIZQ);
      label_11:
      while (true) {
        Codigo();
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case BOOL:
        case VAR:
        case CONST:
        case FOR:
        case WHILE:
        case SI:
        case LEER:
        case ESCRIBIR:
        case VOID:
        case FUNC:
        case IDENTIFICADOR:{
          ;
          break;
          }
        default:
          jj_la1[19] = jj_gen;
          break label_11;
        }
      }
      jj_consume_token(LLAVEDER);
    } catch (ParseException e) {
tabla.add(manejarErrorSintactico(e));
    }
}

  static final public void condicionFor() throws ParseException {
    try {
      tipoDato();
      jj_consume_token(IDENTIFICADOR);
      jj_consume_token(IGUAL);
      jj_consume_token(ENTEROS);
      jj_consume_token(DELIMITADOR);
      jj_consume_token(IDENTIFICADOR);
      OperadoresComparadores();
      valor();
      jj_consume_token(DELIMITADOR);
      operadorIncDec();
      jj_consume_token(IDENTIFICADOR);
    } catch (ParseException e) {
tabla.add(manejarErrorSintactico(e));
    }
}

  static final public void operadorIncDec() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case INC:{
      jj_consume_token(INC);
      break;
      }
    case DEC:{
      jj_consume_token(DEC);
      break;
      }
    default:
      jj_la1[20] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  static final public void SentenciasFunciones() throws ParseException {
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case FUNC:{
        jj_consume_token(FUNC);
        tipoDato();
        jj_consume_token(IDENTIFICADOR);
        jj_consume_token(PARENIZQ);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case IDENTIFICADOR:{
          parametros();
          break;
          }
        default:
          jj_la1[21] = jj_gen;
          ;
        }
        jj_consume_token(PARENDER);
        jj_consume_token(LLAVEIZQ);
        label_12:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case BOOL:
          case VAR:
          case CONST:
          case FOR:
          case WHILE:
          case SI:
          case LEER:
          case ESCRIBIR:
          case VOID:
          case FUNC:
          case IDENTIFICADOR:{
            ;
            break;
            }
          default:
            jj_la1[22] = jj_gen;
            break label_12;
          }
          Codigo();
        }
        jj_consume_token(RETURN);
        valor();
        jj_consume_token(DELIMITADOR);
        jj_consume_token(LLAVEDER);
        jj_consume_token(DELIMITADOR);
        break;
        }
      case VOID:{
        jj_consume_token(VOID);
        jj_consume_token(IDENTIFICADOR);
        jj_consume_token(PARENIZQ);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case IDENTIFICADOR:{
          parametros();
          break;
          }
        default:
          jj_la1[23] = jj_gen;
          ;
        }
        jj_consume_token(PARENDER);
        jj_consume_token(LLAVEIZQ);
        label_13:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case BOOL:
          case VAR:
          case CONST:
          case FOR:
          case WHILE:
          case SI:
          case LEER:
          case ESCRIBIR:
          case VOID:
          case FUNC:
          case IDENTIFICADOR:{
            ;
            break;
            }
          default:
            jj_la1[24] = jj_gen;
            break label_13;
          }
          Codigo();
        }
        jj_consume_token(LLAVEDER);
        jj_consume_token(DELIMITADOR);
        break;
        }
      default:
        jj_la1[25] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException e) {
tabla.add(manejarErrorSintactico(e));
    }
}

  static final public void parametros() throws ParseException {
    try {
      jj_consume_token(IDENTIFICADOR);
      tipoDato();
      label_14:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMA:{
          ;
          break;
          }
        default:
          jj_la1[26] = jj_gen;
          break label_14;
        }
        jj_consume_token(COMA);
        jj_consume_token(IDENTIFICADOR);
        tipoDato();
      }
    } catch (ParseException e) {
tabla.add(manejarErrorSintactico(e));
    }
}

  static final public void llamarFuncion() throws ParseException {
    try {
      jj_consume_token(FUNC);
      jj_consume_token(IDENTIFICADOR);
      jj_consume_token(PARENIZQ);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ENTEROS:
      case NUMERODECIMAL:
      case VCAD:
      case IDENTIFICADOR:{
        valor();
        label_15:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case COMA:{
            ;
            break;
            }
          default:
            jj_la1[27] = jj_gen;
            break label_15;
          }
          jj_consume_token(COMA);
          valor();
        }
        break;
        }
      default:
        jj_la1[28] = jj_gen;
        ;
      }
      jj_consume_token(PARENDER);
      jj_consume_token(DELIMITADOR);
    } catch (ParseException e) {
tabla.add(manejarErrorSintactico(e));
    }
}

  static final public void asignacionConFuncion() throws ParseException {
    try {
      jj_consume_token(FUNC);
      jj_consume_token(IDENTIFICADOR);
      jj_consume_token(PARENIZQ);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ENTEROS:
      case NUMERODECIMAL:
      case VCAD:
      case IDENTIFICADOR:{
        valor();
        label_16:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case COMA:{
            ;
            break;
            }
          default:
            jj_la1[29] = jj_gen;
            break label_16;
          }
          jj_consume_token(COMA);
          valor();
        }
        break;
        }
      default:
        jj_la1[30] = jj_gen;
        ;
      }
      jj_consume_token(PARENDER);
    } catch (ParseException e) {
tabla.add(manejarErrorSintactico(e));
    }
}

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public AnalizadorAqheranTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[31];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x1a00,0x1a00,0x780,0xc0000000,0x0,0x0,0x0,0x0,0x1a00,0x0,0x1a00,0x700000,0x700000,0x3e800000,0x1a00,0xc0000000,0x3e000,0x3e000,0xc0000000,0x1a00,0xc0000,0x0,0x1a00,0x0,0x1a00,0x0,0x0,0x0,0xc0000000,0x0,0xc0000000,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x18801a6,0x18801a6,0x0,0x1000001,0x1000001,0x40000,0x1000001,0x1000001,0x18801a6,0x40,0x18801a6,0x0,0x0,0x0,0x18801a6,0x1800001,0x0,0x0,0x1000001,0x18801a6,0x0,0x1000000,0x18801a6,0x1000000,0x18801a6,0x880000,0x800,0x800,0x1000001,0x800,0x1000001,};
	}

  /** Constructor with InputStream. */
  public AnalizadorAqheran(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public AnalizadorAqheran(java.io.InputStream stream, String encoding) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser.  ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new AnalizadorAqheranTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 31; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 31; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public AnalizadorAqheran(java.io.Reader stream) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new AnalizadorAqheranTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 31; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new AnalizadorAqheranTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 31; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public AnalizadorAqheran(AnalizadorAqheranTokenManager tm) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 31; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(AnalizadorAqheranTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 31; i++) jj_la1[i] = -1;
  }

  static private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }


/** Get the next Token. */
  static final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  static private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;

  /** Generate ParseException. */
  static public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[58];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 31; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 58; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  static private boolean trace_enabled;

/** Trace enabled. */
  static final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

}
