/* Generated By:JavaCC: Do not edit this line. AnalizadorAqheranConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalizadorAqheranConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INT = 7;
  /** RegularExpression Id. */
  int FLOAT = 8;
  /** RegularExpression Id. */
  int BOOL = 9;
  /** RegularExpression Id. */
  int STRING = 10;
  /** RegularExpression Id. */
  int VAR = 11;
  /** RegularExpression Id. */
  int CONST = 12;
  /** RegularExpression Id. */
  int MAS = 13;
  /** RegularExpression Id. */
  int MENOS = 14;
  /** RegularExpression Id. */
  int MULT = 15;
  /** RegularExpression Id. */
  int DIV = 16;
  /** RegularExpression Id. */
  int MOD = 17;
  /** RegularExpression Id. */
  int INC = 18;
  /** RegularExpression Id. */
  int DEC = 19;
  /** RegularExpression Id. */
  int AND = 20;
  /** RegularExpression Id. */
  int OR = 21;
  /** RegularExpression Id. */
  int NOT = 22;
  /** RegularExpression Id. */
  int IGUALDAD = 23;
  /** RegularExpression Id. */
  int IGUAL = 24;
  /** RegularExpression Id. */
  int DESIGUALDAD = 25;
  /** RegularExpression Id. */
  int MAYOR = 26;
  /** RegularExpression Id. */
  int MENOR = 27;
  /** RegularExpression Id. */
  int MAYORIGUAL = 28;
  /** RegularExpression Id. */
  int MENORIGUAL = 29;
  /** RegularExpression Id. */
  int ENTEROS = 30;
  /** RegularExpression Id. */
  int NUMERODECIMAL = 31;
  /** RegularExpression Id. */
  int VCAD = 32;
  /** RegularExpression Id. */
  int FOR = 33;
  /** RegularExpression Id. */
  int WHILE = 34;
  /** RegularExpression Id. */
  int MATRIZ = 35;
  /** RegularExpression Id. */
  int VECTOR = 36;
  /** RegularExpression Id. */
  int SI = 37;
  /** RegularExpression Id. */
  int SINO = 38;
  /** RegularExpression Id. */
  int LEER = 39;
  /** RegularExpression Id. */
  int ESCRIBIR = 40;
  /** RegularExpression Id. */
  int PUNTO = 41;
  /** RegularExpression Id. */
  int DELIMITADOR = 42;
  /** RegularExpression Id. */
  int COMA = 43;
  /** RegularExpression Id. */
  int CORCHIZQ = 44;
  /** RegularExpression Id. */
  int CORCHDER = 45;
  /** RegularExpression Id. */
  int LLAVEIZQ = 46;
  /** RegularExpression Id. */
  int LLAVEDER = 47;
  /** RegularExpression Id. */
  int PARENIZQ = 48;
  /** RegularExpression Id. */
  int PARENDER = 49;
  /** RegularExpression Id. */
  int CONCATENAR = 50;
  /** RegularExpression Id. */
  int VOID = 51;
  /** RegularExpression Id. */
  int RETURN = 52;
  /** RegularExpression Id. */
  int INICIO = 53;
  /** RegularExpression Id. */
  int FIN = 54;
  /** RegularExpression Id. */
  int FUNC = 55;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 56;
  /** RegularExpression Id. */
  int ERROR = 57;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"int\"",
    "\"float\"",
    "\"bool\"",
    "\"string\"",
    "\"@\"",
    "\"#\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"++\"",
    "\"--\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"==\"",
    "\"=\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "<ENTEROS>",
    "<NUMERODECIMAL>",
    "<VCAD>",
    "\"for\"",
    "\"while\"",
    "\"matrix\"",
    "\"vec\"",
    "\"if\"",
    "\"else\"",
    "\"readline\"",
    "\"Aqhe\"",
    "\".\"",
    "\";\"",
    "\",\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"&\"",
    "\"void\"",
    "\"return\"",
    "\"start\"",
    "\"end\"",
    "\"fn\"",
    "<IDENTIFICADOR>",
    "<ERROR>",
  };

}
